/**
 * ENRICHISSEMENT COMPLET ET HARMONISÉ DES CLÉS UI DANS LES 13 LANGUES
 * Garantit qu'aucun libellé statique d'en-tête de section, d'objection, de règle ou de TOC
 * ne retombe sur un fallback français par défaut.
 */

const fs = require('fs');
const path = require('path');

const TRANSLATIONS_DIR = path.join(__dirname, '..', 'js', 'translations');

const uiDictionary = {
  fr: {
    tocThesis: "Leur Thèse",
    tocLogical: "Nœud Logique",
    tocPrinciple: "Principe Central",
    tocQuranic: "Architecture Coranique",
    tocAnalogies: "Analogies",
    tocResponses: "Réponses Prêtes",
    tocObjections: "Objections",
    tocQuiz: "Quiz",
    sec1Header: "1. LEUR THÈSE & LES VERSETS QU'ILS DÉTOURNENT",
    sec1QuestionTitle: "La question réelle à poser :",
    sec2Header: "2. LE NŒUD LOGIQUE DU PROBLÈME",
    sec2GeneralRule: "RÈGLE GÉNÉRALE :",
    sec2ErrorAvoid: "Erreur & Sophisme à Éviter",
    sec3Header: "3. LE PRINCIPE CENTRAL DE RÉFUTATION",
    sec3LogicalTest: "TEST LOGIQUE :",
    sec4Header: "4. L'ARCHITECTURE CORANIQUE COMPLÈTE",
    sec4Consequence: "CONSÉQUENCE :",
    sec5Header: "5. LES ANALOGIES PÉDAGOGIQUES",
    sec6Header: "6. RÉPONSES PRÊTES À L'EMPLOI",
    sec6QuickTitle: "Réponse Éclair (30 Secondes)",
    sec6DevTitle: "Réponse Développée & Argumentée",
    btnCopyQuick: "Copier la réponse 30s en 1 clic",
    sec7Header: "7. OBJECTIONS CORANISTES & LEURS RÉPONSES",
    labelObjection: "Objection",
    labelMethodicAnswer: "Réponse méthodique :",
    sec7DirectQuestions: "Questions de cadrage directes :",
    sec8Header: "8. TESTEZ VOTRE COMPRÉHENSION",
    sec8Sub: "Quiz interactif",
    sec9Header: "9. CONCLUSION EN CHAÎNE LOGIQUE",
    labelSituation: "Situation :",
    labelLogic: "Mécanisme logique :",
    labelLesson: "Enseignement :",
    labelApplication: "Application au débat :",
    btnDownloadOriginalPdf: "Télécharger le PDF original",
    btnPrintPage: "Imprimer / Exporter PDF",
    formulaRetenir: "FORMULE À RETENIR :"
  },
  ar: {
    tocThesis: "شبهتهم والآيات",
    tocLogical: "العقدة المنطقية",
    tocPrinciple: "الأصل المنهجي",
    tocQuranic: "البنية القرآنية",
    tocAnalogies: "الأمثلة القياسية",
    tocResponses: "الردود الجاهزة",
    tocObjections: "الشبهات والردود",
    tocQuiz: "اختبر فهمك",
    sec1Header: "١. شبهتهم والآيات التي يحرفون تأويلها",
    sec1QuestionTitle: "السؤال الحقيقي الواجب طرحه :",
    sec2Header: "٢. العقدة المنطقية والضوابط المنهجية",
    sec2GeneralRule: "القاعدة العامة :",
    sec2ErrorAvoid: "المغالطة المنطقية الواجب الحذر منها",
    sec3Header: "٣. الأصل المنهجي في الرد",
    sec3LogicalTest: "الاختبار المنطقي الحاسم :",
    sec4Header: "٤. البنية القرآنية المتكاملة",
    sec4Consequence: "اللازم الشرعي والنتيجة :",
    sec5Header: "٥. الأمثلة الواقعية المقربة للمعنى",
    sec6Header: "٦. الردود الجاهزة في الحوار",
    sec6QuickTitle: "الرد السريع المباشر (٣٠ ثانية)",
    sec6DevTitle: "الرد المفصل والمؤصل",
    btnCopyQuick: "نسخ الرد السريع بنقرة واحدة",
    sec7Header: "٧. اعتراضاتهم والجواب المنهجي عليها",
    labelObjection: "الاعتراض",
    labelMethodicAnswer: "الجواب المنهجي :",
    sec7DirectQuestions: "أسئلة حاسمة لإلزام الخصم :",
    sec8Header: "٨. اختبر فهمك للمناظرة",
    sec8Sub: "اختبار تفاعلي",
    sec9Header: "٩. الخلاصة والتسلسل المنطقي",
    labelSituation: "الواقعة :",
    labelLogic: "الميزان المنطقي :",
    labelLesson: "الفائدة المنهجية :",
    labelApplication: "تنزيلها على الشبهة :",
    btnDownloadOriginalPdf: "تحميل الكتيب الأصلي (PDF)",
    btnPrintPage: "طباعة / حفظ كملف PDF",
    formulaRetenir: "القاعدة الذهبية :"
  },
  en: {
    tocThesis: "Their Thesis",
    tocLogical: "Logical Node",
    tocPrinciple: "Core Principle",
    tocQuranic: "Quranic Architecture",
    tocAnalogies: "Analogies",
    tocResponses: "Ready Responses",
    tocObjections: "Objections",
    tocQuiz: "Quiz",
    sec1Header: "1. THEIR THESIS & DISTORTED VERSES",
    sec1QuestionTitle: "The essential question to ask:",
    sec2Header: "2. THE LOGICAL NODE OF THE ARGUMENT",
    sec2GeneralRule: "GENERAL RULE:",
    sec2ErrorAvoid: "Fallacy & Error to Avoid",
    sec3Header: "3. THE CENTRAL PRINCIPLE OF REFUTATION",
    sec3LogicalTest: "LOGICAL TEST:",
    sec4Header: "4. THE COMPLETE QURANIC ARCHITECTURE",
    sec4Consequence: "CONSEQUENCE:",
    sec5Header: "5. PRACTICAL REAL-WORLD ANALOGIES",
    sec6Header: "6. READY-TO-USE DEBATE RESPONSES",
    sec6QuickTitle: "Lightning Response (30 Seconds)",
    sec6DevTitle: "Comprehensive & Detailed Response",
    btnCopyQuick: "Copy 30s response in 1 click",
    sec7Header: "7. QURANIST OBJECTIONS & METHODICAL ANSWERS",
    labelObjection: "Objection",
    labelMethodicAnswer: "Methodical Answer:",
    sec7DirectQuestions: "Direct Framing Questions:",
    sec8Header: "8. TEST YOUR UNDERSTANDING",
    sec8Sub: "Interactive Quiz",
    sec9Header: "9. CONCLUSION IN LOGICAL CHAIN",
    labelSituation: "Situation:",
    labelLogic: "Logical Mechanism:",
    labelLesson: "Core Lesson:",
    labelApplication: "Application to Debate:",
    btnDownloadOriginalPdf: "Download original PDF",
    btnPrintPage: "Print / Export as PDF",
    formulaRetenir: "CORE TAKEAWAY FORMULA:"
  },
  es: {
    tocThesis: "Su Tesis",
    tocLogical: "Nudo Lógico",
    tocPrinciple: "Principio Central",
    tocQuranic: "Arquitectura Coránica",
    tocAnalogies: "Analogías",
    tocResponses: "Respuestas Listas",
    tocObjections: "Objeciones",
    tocQuiz: "Cuestionario",
    sec1Header: "1. SU TESIS Y LOS VERSÍCULOS QUE DESVÍAN",
    sec1QuestionTitle: "La pregunta real que se debe plantear:",
    sec2Header: "2. EL NUDO LÓGICO DEL PROBLEMA",
    sec2GeneralRule: "REGLA GENERAL:",
    sec2ErrorAvoid: "Error y Falacia a Evitar",
    sec3Header: "3. EL PRINCIPIO CENTRAL DE REFUTACIÓN",
    sec3LogicalTest: "PRUEBA LÓGICA:",
    sec4Header: "4. LA ARQUITECTURA CORÁNICA COMPLETA",
    sec4Consequence: "CONSECUENCIA:",
    sec5Header: "5. LAS ANALOGÍAS PEDAGÓGICAS",
    sec6Header: "6. RESPUESTAS LISTAS PARA EL DIÁLOGO",
    sec6QuickTitle: "Respuesta Rápida (30 Segundos)",
    sec6DevTitle: "Respuesta Desarrollada y Argumentada",
    btnCopyQuick: "Copiar la respuesta de 30s en 1 clic",
    sec7Header: "7. OBJECIONES CORANISTAS Y SUS RESPUESTAS",
    labelObjection: "Objeción",
    labelMethodicAnswer: "Respuesta metódica:",
    sec7DirectQuestions: "Preguntas de encuadre directo:",
    sec8Header: "8. PON A PRUEBA TU COMPRENSIÓN",
    sec8Sub: "Cuestionario interactivo",
    sec9Header: "9. CONCLUSIÓN EN CADENA LÓGICA",
    labelSituation: "Situación:",
    labelLogic: "Mecanismo lógico:",
    labelLesson: "Enseñanza:",
    labelApplication: "Aplicación al debate:",
    btnDownloadOriginalPdf: "Descargar el PDF original",
    btnPrintPage: "Imprimir / Guardar como PDF",
    formulaRetenir: "FÓRMULA CLAVE A RECORDAR:"
  },
  it: {
    tocThesis: "La Loro Tesi",
    tocLogical: "Nodo Logico",
    tocPrinciple: "Principio Centrale",
    tocQuranic: "Architettura Coranica",
    tocAnalogies: "Analogie",
    tocResponses: "Risposte Pronte",
    tocObjections: "Obiezioni",
    tocQuiz: "Quiz",
    sec1Header: "1. LA LORO TESI E I VERSETTI DEVIATI",
    sec1QuestionTitle: "La vera domanda da porre:",
    sec2Header: "2. IL NODO LOGICO DEL PROBLEMA",
    sec2GeneralRule: "REGOLA GENERALE:",
    sec2ErrorAvoid: "Errore e Fallacia da Evitare",
    sec3Header: "3. IL PRINCIPIO CENTRALE DI CONFUTAZIONE",
    sec3LogicalTest: "TEST LOGICO:",
    sec4Header: "4. L'ARCHITETTURA CORANICA COMPLETA",
    sec4Consequence: "CONSEGUENZA:",
    sec5Header: "5. LE ANALOGIE PEDAGOGICHE",
    sec6Header: "6. RISPOSTE PRONTE ALL'USO",
    sec6QuickTitle: "Risposta Lampo (30 Secondi)",
    sec6DevTitle: "Risposta Sviluppata e Argomentata",
    btnCopyQuick: "Copia la risposta di 30s in 1 clic",
    sec7Header: "7. OBIEZIONI CORANISTE E RISPOSTE METODICHE",
    labelObjection: "Obiezione",
    labelMethodicAnswer: "Risposta metodica:",
    sec7DirectQuestions: "Domande di inquadramento diretto:",
    sec8Header: "8. METTI ALLA PROVA LA TUA COMPRENSIONE",
    sec8Sub: "Quiz interattivo",
    sec9Header: "9. CONCLUSIONE IN CATENA LOGICA",
    labelSituation: "Situazione:",
    labelLogic: "Meccanismo logico:",
    labelLesson: "Insegnamento:",
    labelApplication: "Applicazione al dibattito:",
    btnDownloadOriginalPdf: "Scarica il PDF originale",
    btnPrintPage: "Stampa / Salva come PDF",
    formulaRetenir: "FORMULA CHIAVE DA RICORDARE:"
  },
  pt: {
    tocThesis: "A Sua Tese",
    tocLogical: "Nó Lógico",
    tocPrinciple: "Princípio Central",
    tocQuranic: "Arquitetura Alcorânica",
    tocAnalogies: "Analogias",
    tocResponses: "Respostas Prontas",
    tocObjections: "Objeções",
    tocQuiz: "Questionário",
    sec1Header: "1. A SUA TESE E OS VERSÍCULOS QUE DESVIAM",
    sec1QuestionTitle: "A pergunta real a ser feita:",
    sec2Header: "2. O NÓ LÓGICO DO PROBLEMA",
    sec2GeneralRule: "REGRA GERAL:",
    sec2ErrorAvoid: "Erro e Falácia a Evitar",
    sec3Header: "3. O PRINCÍPIO CENTRAL DE REFUTAÇÃO",
    sec3LogicalTest: "TESTE LÓGICO:",
    sec4Header: "4. A ARQUITETURA ALCORÂNICA COMPLETA",
    sec4Consequence: "CONSEQUÊNCIA:",
    sec5Header: "5. AS ANALOGIAS PEDAGÓGICAS",
    sec6Header: "6. RESPOSTAS PRONTAS PARA O DIÁLOGO",
    sec6QuickTitle: "Resposta Rápida (30 Segundos)",
    sec6DevTitle: "Resposta Desenvolvida e Argumentada",
    btnCopyQuick: "Copiar resposta de 30s em 1 clique",
    sec7Header: "7. OBJEÇÕES CORANISTAS E RESPOSTAS METÓDICAS",
    labelObjection: "Objeção",
    labelMethodicAnswer: "Resposta metódica:",
    sec7DirectQuestions: "Perguntas de enquadramento direto:",
    sec8Header: "8. TESTE A SUA COMPREENSÃO",
    sec8Sub: "Questionário interativo",
    sec9Header: "9. CONCLUSÃO EM CADEIA LÓGICA",
    labelSituation: "Situação:",
    labelLogic: "Mecanismo lógico:",
    labelLesson: "Ensinamento:",
    labelApplication: "Aplicação ao debate:",
    btnDownloadOriginalPdf: "Baixar o PDF original",
    btnPrintPage: "Imprimir / Salvar como PDF",
    formulaRetenir: "FÓRMULA PRINCIPAL A RETER:"
  },
  de: {
    tocThesis: "Ihre These",
    tocLogical: "Logischer Knoten",
    tocPrinciple: "Zentrales Prinzip",
    tocQuranic: "Koranische Architektur",
    tocAnalogies: "Analogien",
    tocResponses: "Bereite Antworten",
    tocObjections: "Einwände",
    tocQuiz: "Quiz",
    sec1Header: "1. IHRE THESE & DIE FEHLINTERPRETIERTEN VERSE",
    sec1QuestionTitle: "Die eigentliche Frage, die gestellt werden muss:",
    sec2Header: "2. DER LOGISCHE KNOTEN DES PROBLEMS",
    sec2GeneralRule: "ALLGEMEINE REGEL:",
    sec2ErrorAvoid: "Zu vermeidender Trugschluss & Denkfehler",
    sec3Header: "3. DAS ZENTRALE WIDERLEGUNGSPRINZIP",
    sec3LogicalTest: "LOGISCHER TEST:",
    sec4Header: "4. DIE VOLLSTÄNDIGE KORANISCHE ARCHITEKTUR",
    sec4Consequence: "LOGISCHE FOLGE:",
    sec5Header: "5. PÄDAGOGISCHE ALLTAGSANALOGIEN",
    sec6Header: "6. SOFORT EINSETZBARE ANTWORTEN",
    sec6QuickTitle: "Blitzantwort (30 Sekunden)",
    sec6DevTitle: "Ausführliche & Begründete Antwort",
    btnCopyQuick: "30s-Antwort mit 1 Klick kopieren",
    sec7Header: "7. KORANISTISCHE EINWÄNDE & METHODISCHE ANTWORTEN",
    labelObjection: "Einwand",
    labelMethodicAnswer: "Methodische Antwort:",
    sec7DirectQuestions: "Direkte Leitfragen:",
    sec8Header: "8. TESTEN SIE IHR VERSTÄNDNIS",
    sec8Sub: "Interaktives Quiz",
    sec9Header: "9. LOGISCHE SCHLUSSFOLGERUNGSKETTE",
    labelSituation: "Situation:",
    labelLogic: "Logischer Mechanismus:",
    labelLesson: "Kernlehre:",
    labelApplication: "Anwendung auf die Debatte:",
    btnDownloadOriginalPdf: "Originale PDF-Broschüre herunterladen",
    btnPrintPage: "Drucken / Als PDF speichern",
    formulaRetenir: "KERNFORMEL ZUM MERKEN:"
  },
  ur: {
    tocThesis: "ان کا شبہ اور آیات",
    tocLogical: "منطقی گرہ",
    tocPrinciple: "بنیادی اصول",
    tocQuranic: "قرآنی ساخت",
    tocAnalogies: "عملی مثالیں",
    tocResponses: "تیار جوابات",
    tocObjections: "اعتراضات اور جوابات",
    tocQuiz: "فہم کی آزمائش",
    sec1Header: "۱. ان کا شبہ اور سیاق سے ہٹائی گئی آیات",
    sec1QuestionTitle: "حقیقی سوال جو پوچھا جانا چاہیے :",
    sec2Header: "۲. مسئلے کی منطقی گرہ اور ضوابط",
    sec2GeneralRule: "عام قاعدہ :",
    sec2ErrorAvoid: "وہ منطقی مغالطہ جس سے بچنا ضروری ہے",
    sec3Header: "۳. رد کا بنیادی اور محکم اصول",
    sec3LogicalTest: "فیصلہ کن منطقی امتحان :",
    sec4Header: "۴. مکمل قرآنی فریم ورک",
    sec4Consequence: "لازمی شرعی نتیجہ :",
    sec5Header: "۵. روزمرہ زندگی کی تفہیمی مثالیں",
    sec6Header: "۶. مناظرے کے لیے فوری تیار جوابات",
    sec6QuickTitle: "تیز ترین جواب (۳۰ سیکنڈ)",
    sec6DevTitle: "تفصیلی اور مدلل جواب",
    btnCopyQuick: "۳۰ سیکنڈ کا جواب ایک کلک میں کاپی کریں",
    sec7Header: "۷. منکرین کے اعتراضات اور ان کا منہجی رد",
    labelObjection: "اعتراض",
    labelMethodicAnswer: "منہجی جواب :",
    sec7DirectQuestions: "بنیادی راہنما سوالات :",
    sec8Header: "۸. اپنے فہم کی آزمائش کریں",
    sec8Sub: "انٹرایکٹو کوئز",
    sec9Header: "۹. منطقی نتیجے کا تسلسل",
    labelSituation: "واقعہ / صورتحال :",
    labelLogic: "منطقی میزان :",
    labelLesson: "حاصل شدہ سبق :",
    labelApplication: "شبہے پر اطلاق :",
    btnDownloadOriginalPdf: "اصل پی ڈی ایف کتابچہ ڈاؤن لوڈ کریں",
    btnPrintPage: "پرنٹ کریں / بطور پی ڈی ایف محفوظ کریں",
    formulaRetenir: "یاد رکھنے کے لیے سنہری فارمولا :"
  },
  ta: {
    tocThesis: "அவர்களின் வாதம்",
    tocLogical: "தர்க்க முடிச்சு",
    tocPrinciple: "மையக் கோட்பாடு",
    tocQuranic: "திருக்குர்ஆன் கட்டமைப்பு",
    tocAnalogies: "உவமைகள்",
    tocResponses: "தயார் பதில்கள்",
    tocObjections: "மறுப்புகள்",
    tocQuiz: "தேர்வு",
    sec1Header: "1. அவர்களின் வாதமும் திசைதிருப்பப்படும் வசனங்களும்",
    sec1QuestionTitle: "கேட்கப்பட வேண்டிய உண்மையான கேள்வி :",
    sec2Header: "2. பிரச்சினையின் தர்க்க முடிச்சு",
    sec2GeneralRule: "பொது விதி :",
    sec2ErrorAvoid: "தவிர்க்க வேண்டிய தர்க்கப் பிழை",
    sec3Header: "3. மறுப்பின் மையக் கோட்பாடு",
    sec3LogicalTest: "தர்க்கச் சோதனை :",
    sec4Header: "4. முழுமையான திருக்குர்ஆன் கட்டமைப்பு",
    sec4Consequence: "இன்றியமையாத மார்க்க முடிவு :",
    sec5Header: "5. கற்பித்தல் உவமைகள்",
    sec6Header: "6. உரையாடலுக்கான தயார் பதில்கள்",
    sec6QuickTitle: "மின்னல் வேகப் பதில் (30 வினாடிகள்)",
    sec6DevTitle: "விரிவான மற்றும் ஆதாரபூர்வமான பதில்",
    btnCopyQuick: "30 வினாடி பதிலை 1 கிளிக்கில் நகலெடுக்கவும்",
    sec7Header: "7. குர்ஆனியர்களின் மறுப்புகளும் முறையான பதில்களும்",
    labelObjection: "மறுப்பு",
    labelMethodicAnswer: "முறையான பதில் :",
    sec7DirectQuestions: "நேரடி வழிகாட்டும் கேள்விகள் :",
    sec8Header: "8. உங்கள் புரிதலைச் சோதிக்கவும்",
    sec8Sub: "ஊடாடும் தேர்வு",
    sec9Header: "9. தர்க்கச் சங்கிலி முடிவு",
    labelSituation: "சூழ்நிலை :",
    labelLogic: "தர்க்க வழிமுறை :",
    labelLesson: "கற்க வேண்டிய பாடம் :",
    labelApplication: "விவாதத்தில் பயன்படுத்துதல் :",
    btnDownloadOriginalPdf: "அசல் PDF கையேட்டைப் பதிவிறக்கவும்",
    btnPrintPage: "அச்சிடுக / PDF ஆகச் சேமிக்கவும்",
    formulaRetenir: "நினைவில் கொள்ள வேண்டிய பொன்மொழி :"
  },
  ary: {
    tocThesis: "الشبهة ديالهم والآيات",
    tocLogical: "العقدة المنطقية",
    tocPrinciple: "الأصل المنهجي",
    tocQuranic: "البنية القرآنية",
    tocAnalogies: "الأمثلة القياسية",
    tocResponses: "الأجوبة الواجدة",
    tocObjections: "الشبهات والأجوبة",
    tocQuiz: "امتحان الفهم",
    sec1Header: "1. الشبهة ديالهم والآيات اللي كيحرفو المعنى ديالها",
    sec1QuestionTitle: "السؤال الحقيقي اللي خاصك تطرحو :",
    sec2Header: "2. العقدة المنطقية والضوابط المنهجية",
    sec2GeneralRule: "القاعدة العامة :",
    sec2ErrorAvoid: "المغالطة المنطقية اللي خاصك ترد منها البال",
    sec3Header: "3. الأصل المنهجي فالرد",
    sec3LogicalTest: "الامتحان المنطقي الحاسم :",
    sec4Header: "4. البنية القرآنية المتكاملة",
    sec4Consequence: "اللازم الشرعي والنتيجة :",
    sec5Header: "5. الأمثلة الواقعية اللي كتبسط الفهم",
    sec6Header: "6. الأجوبة الواجدة للنقاش والحوار",
    sec6QuickTitle: "الجواب السريع المباشر (30 ثانية)",
    sec6DevTitle: "الجواب المفصل والمؤصل",
    btnCopyQuick: "كوبي الجواب ديال 30 ثانية فكليكة وحدة",
    sec7Header: "7. الشبهات ديالهم والجواب المنهجي عليها",
    labelObjection: "الشبهة",
    labelMethodicAnswer: "الجواب المنهجي :",
    sec7DirectQuestions: "أسئلة حاسمة لإحراج الخصم :",
    sec8Header: "8. تيستي الفهم ديالك",
    sec8Sub: "كويز تفاعلي",
    sec9Header: "9. الخلاصة والتسلسل المنطقي",
    labelSituation: "الواقعة :",
    labelLogic: "الميزان المنطقي :",
    labelLesson: "الفائدة المنهجية :",
    labelApplication: "التطبيق على الشبهة :",
    btnDownloadOriginalPdf: "تيليشارجي الكتيب الأصلي (PDF)",
    btnPrintPage: "طبع / حفظ بصيغة PDF",
    formulaRetenir: "القاعدة الذهبية اللي خاصك تعقل عليها :"
  },
  ps: {
    tocThesis: "د هغوی شبهه او آیاتونه",
    tocLogical: "منطقي غوټه",
    tocPrinciple: "بنسټیز اصل",
    tocQuranic: "قرآني چوکاټ",
    tocAnalogies: "عملي مثالونه",
    tocResponses: "تیار ځوابونه",
    tocObjections: "اعتراضونه او ځوابونه",
    tocQuiz: "د پوهې ازموینه",
    sec1Header: "۱. د هغوی شبهه او له سیاق څخه ایستل شوي آیاتونه",
    sec1QuestionTitle: "اصلي پوښتنه چې باید وپوښتل شي :",
    sec2Header: "۲. د مسلې منطقي غوټه او اصول",
    sec2GeneralRule: "عمومي قاعده :",
    sec2ErrorAvoid: "هغه منطقي تېروتنه چې باید ډډه ترې وشي",
    sec3Header: "۳. د رد بنسټیز او غښتلی اصل",
    sec3LogicalTest: "پرېکنده منطقي ازموینه :",
    sec4Header: "۴. بشپړ قرآني چوکاټ",
    sec4Consequence: "لازمي شرعي پایله :",
    sec5Header: "۵. د ورځني ژوند پوهوونکي مثالونه",
    sec6Header: "۶. د بحث لپاره چمتو ځوابونه",
    sec6QuickTitle: "چټک مستقیم ځواب (۳۰ ثانیې)",
    sec6DevTitle: "تفصیلي او مستند ځواب",
    btnCopyQuick: "د ۳۰ ثانیو ځواب په یو کلیک کاپي کړئ",
    sec7Header: "۷. د منکرینو اعتراضونه او د هغوی منهجي ځوابونه",
    labelObjection: "اعتراض",
    labelMethodicAnswer: "منهجي ځواب :",
    sec7DirectQuestions: "لارښوونکې مستقیمې پوښتنې :",
    sec8Header: "۸. خپله پوهه وازمویئ",
    sec8Sub: "تعاملي کوئز",
    sec9Header: "۹. د منطقي پایلې تسلسل",
    labelSituation: "حالت / پېښه :",
    labelLogic: "منطقي تله :",
    labelLesson: "ترلاسه شوی درس :",
    labelApplication: "په شبهه تطبیق :",
    btnDownloadOriginalPdf: "اصلي پی ډي ایف رساله ډاونلوډ کړئ",
    btnPrintPage: "چاپ کړئ / د PDF په توګه خوندي کړئ",
    formulaRetenir: "د یادولو لپاره زرین فرمول :"
  },
  ku: {
    tocThesis: "Îdiaya Wan",
    tocLogical: "Girêka Mantiqî",
    tocPrinciple: "Bingeha Sereke",
    tocQuranic: "Mîmariya Qur'anî",
    tocAnalogies: "Nimûne",
    tocResponses: "Bersivên Amade",
    tocObjections: "Îtîraz",
    tocQuiz: "Quiz",
    sec1Header: "1. ÎDIAYA WAN Û AYETÊN KU JI ÇARÇOVEYÊ DERDIXIN",
    sec1QuestionTitle: "Pirsa rastîn a ku divê were kirin :",
    sec2Header: "2. GIRÊKA MANTIQÎ YA PIRSGIRÊKÊ",
    sec2GeneralRule: "RÊZIKA GIŞTÎ :",
    sec2ErrorAvoid: "Çewtî û Mugaleteya ku Divê Jê Dûr Bikevin",
    sec3Header: "3. BINGEHA SEREKE YA PÛÇKIRINÊ",
    sec3LogicalTest: "TESTA MANTIQÎ :",
    sec4Header: "4. MÎMARIYA QUR'ANÎ YA TEMAM",
    sec4Consequence: "ENCAMA DÎNÎ :",
    sec5Header: "5. MÎNAKÊN PERWERDEHIYÊ YÊN ROJANE",
    sec6Header: "6. BERSIVÊN AMADE YÊN DIYALOGÊ",
    sec6QuickTitle: "Bersiva Birûskî (30 Çirke)",
    sec6DevTitle: "Bersiva Berfireh û Bi Delîl",
    btnCopyQuick: "Bersiva 30ç bi 1 klîkê kopî bike",
    sec7Header: "7. ÎTÎRAZÊN QUR'ANÎYAN Û BERSIVÊN ZANISTÎ",
    labelObjection: "Îtîraz",
    labelMethodicAnswer: "Bersiva zanistî :",
    sec7DirectQuestions: "Pirsên rasterast ên arastekirî :",
    sec8Header: "8. FÊHMKIRINA XWE BIPÎVIN",
    sec8Sub: "Quizê înteraktîf",
    sec9Header: "9. ENCAM DI ZINCÎRA MANTIQÊ DE",
    labelSituation: "Rewş :",
    labelLogic: "Rêbaza mantiqî :",
    labelLesson: "Dersa sereke :",
    labelApplication: "Sepandina li ser nîqaşê :",
    btnDownloadOriginalPdf: "Broşûra orîjînal daxe (PDF)",
    btnPrintPage: "Çap bike / Wek PDF tomar bike",
    formulaRetenir: "FORMÛLA SEREKE YA BÎRANÎNÊ :"
  },
  ce: {
    tocThesis: "Царан Ойла",
    tocLogical: "Логикан Дакъа",
    tocPrincipe: "Коьрта Принцип",
    tocQuranic: "Къуръанан Структура",
    tocAnalogies: "Масалш",
    tocResponses: "Кийча Жоьпаш",
    tocObjections: "Шеконаш",
    tocQuiz: "Тест",
    sec1Header: "1. ЦАРАН ТЕЗИС А, КОНТЕКСТЕРА ДАЬХНА АЯТАШ А",
    sec1QuestionTitle: "Дала деза коьрта бакъ хаттар :",
    sec2Header: "2. ХЬОЛАН ЛОГИКАН ГИРДЕЛ А, БАРАМАШ А",
    sec2GeneralRule: "ЙУКЪАРА БАКЪО :",
    sec2ErrorAvoid: "Ӏадъйитан еза логикан гӀалат а, мугалете а",
    sec3Header: "3. ДУЬХЬАЛО ЯРАН КОЬРТА ПРИНЦИП",
    sec3LogicalTest: "ЛОГИКАН ТЕСТ :",
    sec4Header: "4. КЪУРЪАНИН ЮЬЗЗИНА СТРУКТУРА",
    sec4Consequence: "ДИНАН БИЛГАЛДОЛУ ЖАМӀ :",
    sec5Header: "5. ДАХАРАН ХЬЕХАМИЙН МАСАЛШ",
    sec6Header: "6. КЪАМЕЛАН КИЙЧА ЖОЬПАШ",
    sec6QuickTitle: "Сих Жоп (30 Секунд)",
    sec6DevTitle: "КӀоргера а, Далилца а Долу Жоп",
    btnCopyQuick: "30 секундан жоп цхьана басарца схьаэца",
    sec7Header: "7. КЪУРЪАНИТАШНА ШЕКОНАШ А, ЦАРАН ЖОЬПАШ А",
    labelObjection: "Шеко",
    labelMethodicAnswer: "Ӏилманан жоп :",
    sec7DirectQuestions: "ТӀехьожийна коьрта хаттарш :",
    sec8Header: "8. ХЬАЙН КХЕТАМ ТЕЛЛА",
    sec8Sub: "Интерактивни тест",
    sec9Header: "9. ТӀАЬХЬАЛОНАН ЛОГИКАН ЗӀЕ",
    labelSituation: "Хьал :",
    labelLogic: "Логикан механизм :",
    labelLesson: "Коьрта Ӏамор :",
    labelApplication: "Къовсамехь лелор :",
    btnDownloadOriginalPdf: "Оригинал брошюра схьаэца (PDF)",
    btnPrintPage: "Зорба тоха / PDF санна Ӏалашде",
    formulaRetenir: "ИЭХЬ ЛАТТО ЕЗА КОЬРТА ФОРМУЛА :"
  }
};

Object.keys(uiDictionary).forEach(lang => {
  const filePath = path.join(TRANSLATIONS_DIR, `${lang}.js`);
  if (!fs.existsSync(filePath)) return;

  const raw = fs.readFileSync(filePath, 'utf8');
  const sandbox = {};
  new Function('window', 'sandbox', raw + `\nsandbox.DATA = window.I18N_DATA["${lang}"];`)({}, sandbox);
  const data = sandbox.DATA;

  const extraKeys = uiDictionary[lang];
  data.ui = Object.assign({}, extraKeys, data.ui, extraKeys);

  const header = `/**
 * TRADUCTION OFFICIELLE (${data.name.toUpperCase()} - ${data.native})
 * Manuel de réfutation méthodique du coranisme — Par Salah Eddine Ahmed (Abou Soulaymane)
 */

window.I18N_DATA = window.I18N_DATA || {};
window.I18N_DATA["${lang}"] = ${JSON.stringify(data, null, 2)};
`;

  fs.writeFileSync(filePath, header, 'utf8');
  console.log(`✅ UI enrichi pour ${lang.toUpperCase()} !`);
});
