/**
 * Generateur complet des 11 packs de langue pour le Manuel de Refutation du Coranisme
 * Langues : fr, ar, en, es, de, it, pt, ur, ta, ps, ary
 */

const fs = require('fs');
const path = require('path');

const TRANSLATIONS_DIR = path.join(__dirname, '..', 'js', 'translations');
if (!fs.existsSync(TRANSLATIONS_DIR)) {
  fs.mkdirSync(TRANSLATIONS_DIR, { recursive: true });
}

// Charger FR d'abord
const frData = fs.readFileSync(path.join(TRANSLATIONS_DIR, 'fr.js'), 'utf8');
const frSandbox = {};
new Function('window', frData + '\nwindow.FR_DATA = window.I18N_DATA["fr"];')(frSandbox);
const FR = frSandbox.FR_DATA;

console.log('Chargement FR réussi.');

// UI STRINGS PAR LANGUE
const UI_TRANSLATIONS = {
  ar: {
    brandBadge: "دليل عملي",
    brandTitle: "دليل تفنيد القرآنيين",
    brandSubtitle: "كيف تكشف وترد على شبهات منكري السنة النبوية",
    searchBtn: "بحث",
    barbahariBtn: "البربهاري",
    contactBtn: "اتصال",
    legalBtn: "المشاركة والرخصة",
    summaryTitle: "الفهرس",
    rubriquesCount: "12 فقرة",
    heroTag1: "دليل عملي منهجي للتفنيد",
    heroTag2: "نشر علمي مجاني مفتوح",
    heroTitleMain: "تفنيد",
    heroTitleSpan: "شبهات القرآنيين",
    heroAuthor: "بقلم صلاح الدين أحمد — كيف تكشف وترد على شبهات منكري السنة : 10 شبهات رئيسية مفندة منهجياً",
    heroDesc: "تفكيك مغالطات وشبهات منكري السنة النبوية خطوة بخطوة بالاستدلال المنطقي الرصين، والأمثلة التعليمية، والآيات القرآنية المحكمة، والردود الموجزة في 30 ثانية. نشر ودراسة مجانية نصرة للحق.",
    btnStartArg1: "البدء بالشبهة الأولى",
    btnSearchModal: "بحث عن موضوع / آية",
    btnContactAuthor: "مراسلة المؤلف",
    sommaireTitle: "الشبهات العشر الكبرى مفندة بالتفصيل",
    sommaireBadge: "10 بطاقات علمية جاهزة",
    btnReadCard: "فتح البطاقة",
    btnDownloadPdf: "تحميل الملف الأصلي PDF",
    btnPrintCard: "طباعة أو حفظ البطاقة PDF",
    goldenRuleHeader: "القاعدة الذهبية لمناظرة منكري السنة",
    goldenRuleTitle: "إياك أن تدع المحاور يشتت الموضوع أو يغير مسار النقاش",
    goldenRuleDesc: "أغلب شبهات القرآنيين تقوم على الخلط المنهجي : الخلط بين أصل حجية السنة (المثبتة بالقرآن) وبين مسألة التدوين والرواية التاريخية للكتب المتأخرة.",
    goldenRuleStep1: "1. إثبات ما أمر به القرآن أولاً (الطاعة، التحكيم، البيان، الأسوة الحسنة).",
    goldenRuleStep2: "2. بيان أن السلطة المفوضة للنبي ﷺ من الله لا تنازع السيادة الإلهية بل تنبثق منها.",
    goldenRuleStep3: "3. معالجة مسألة التوثيق التاريخي وسند الرواية بمنهجية علمية.",
    searchModalTitle: "بحث سريع في الدليل",
    searchPlaceholder: "مثال: الصلاة، سورة النحل آية 44، الرواية، الحجية...",
    contactModalTitle: "مراسلة المؤلف والملاحظات",
    contactAuthorBio: "مؤلف كتاب « كيف تكشف وترد على شبهات القرآنيين — منهجية، شبهات، اعتراضات وردود ».",
    contactEmailBoxTitle: "البريد الإلكتروني الرسمي للتواصل :",
    contactSuggestions: "يمكنكم إرسال ملاحظاتكم واقتراحاتكم وأسئلتكم عبر البريد الإلكتروني إلى ideoise@gmail.com.",
    legalModalTitle: "شروط النشر والمشاركة والخصوصية",
    legalSharingTitle: "شروط النشر والاستخدام التعليمي",
    legalSharingSubtitle: "نشر ومشاركة تعليمية مفتوحة",
    legalSharingMainText: "يجوز مشاركة هذا المحتوى مجاناً وإعادة طباعته واستخدامه لأغراض شخصية وتعليمية ودعوية بشرط عزو الحقوق للمؤلف والمصدر.",
    legalAuthorizedUses: "الاستخدامات المسموحة : التحميل والطباعة والمطالعة والمشاركة المجانية في الحلقات العلمية والدروس والمناظرات وشبكات التواصل.",
    legalPrivacyTitle: "البيانات التقنية والخصوصية",
    legalPrivacySubtitle: "سياسة خصوصية مطابقة للوظائف الفعلية للموقع",
    legalPrivacyText: "لا يطلب الموقع إنشاء أي حساب ولا يجمع أي بيانات شخصية عبر النماذج.",
    footerQuote: "« وَإِذَا سَمِعْتَ الرَّجُلَ يَأْتِيهِ الْأَثَرُ فَلَا يُرِيدُهُ، وَيُرِيدُ الْقُرْآنَ، فَلَا تَشُكَّ أَنَّهُ رَجُلٌ قَدِ احْتَوَى عَلَى الزَّنْدَقَةِ، وَقُمْ مِنْ عِنْدِهِ وَدَعْهُ »",
    footerAuthorRef: "— الإمام البربهاري (شرح السنة، فقرة 135)",
    footerNotice: "دليل منهجي مبني على مؤلف الشيخ صلاح الدين أحمد.",
    footerNotice2: "محتوى مجاني متاح للمشاركة والاستفادة التعليمية مع ذكر المصدر.",
    portalWarningBadge: "تحذير أئمة السلف من الطاعنين في النقل والآثار",
    portalTitle: "كلام الإمام البربهاري (رحمه الله)",
    portalEnterBtn: "الدخول إلى دليل التفنيد",
    portalAuthorBadge: "✍️ الإمام البربهاري (ت 329 هـ)",
    portalSourceRef: "📖 المصدر : شرح السنة (فقرة 135)",
    portalDisclaimer: "دليل تفنيد شبهات القرآنيين • بقلم صلاح الدين أحمد • نشر تعليمي متاح",
    argBadgeGiant: "الشبهة",
    btnDownloadOriginalPdf: "تحميل الكتيب PDF",
    btnPrintPage: "طباعة / تصدير PDF",
    formulaRetenir: "القاعدة الذهبية للحفظ :",
    tocTitle: "فهرس محتويات البطاقة",
    tocThesis: "شبهتهم",
    tocLogical: "العقدة المنطقية",
    tocPrinciple: "الأصل المحكم",
    tocQuranic: "البنيان القرآني",
    tocAnalogies: "الأمثلة المقربة",
    tocResponses: "الردود الجاهزة",
    tocObjections: "تفكيك الاعتراضات",
    tocQuiz: "اختبار الفهم",
    tocConclusion: "الخلاصة المنطقية",
    sec1Header: "1. شبهتهم والآيات التي يحرفون معناها",
    sec1Sub: "عرض دعوى منكري السنة وتفكيكها",
    sec1CoranistTitle: "دعوى القرآنيين مكشوفة",
    sec1VersesTitle: "الآيات التي يستدل بها منكر السنة",
    sec1QuestionTitle: "السؤال الحقيقي الجوهري",
    sec2Header: "2. العقدة المنطقية وكشف الخلط",
    sec2Sub: "تفكيك الالتباسات والمغالطات المفاهيمية",
    sec2GeneralRule: "القاعدة المنطقية العامة :",
    sec2ErrorAvoid: "الخطأ الذي ينبغي تجنبه :",
    sec3Header: "3. الأصل المحكم في التفنيد",
    sec3Sub: "الحجة الدامغة التي لا تنكسر",
    sec3FormalScheme: "البناء المنطقي القياسي",
    sec3Explanation: "البيان العقلي والشرعي",
    sec3LogicalTest: "الاختبار المنطقي الحاسم :",
    sec4Header: "4. البنيان القرآني لحجية السنة",
    sec4Sub: "الآيات المحكمات القاطعة لشبهات القرآنيين",
    sec4VersesRef: "الآيات القرآنية المحكمة",
    sec4Consequence: "النتيجة الشرعية الحتمية :",
    sec5Header: "5. الأمثلة التعليمية المقربة للأذهان",
    sec5Sub: "لإيصال الحجة في 30 ثانية",
    sec6Header: "6. الردود الجاهزة للصياغة والمشاركة",
    sec6Sub: "نماذج ردود فورية ومفصلة",
    sec6QuickTitle: "الرد السريع (30 ثانية)",
    btnCopyQuick: "نسخ الرد السريع بنقرة واحدة",
    sec6DevTitle: "الرد المفصل والمبرهن",
    sec7Header: "7. اعتراضات القرآنيين والردود عليها",
    sec7Sub: "توقع كل اعتراض ورد عليه بحكمة وحجة",
    sec7ClickToggle: "انقر على أي اعتراض لعرض الرد المنهجي المباشر :",
    sec7DirectQuestions: "أسئلة الإلزام المباشرة :",
    sec8Header: "8. اختبر فهمك",
    sec8Sub: "اختبار تفاعلي حول الشبهة",
    sec8ValidateBtn: "تأكيد الإجابة",
    sec9Header: "9. النتيجة والتسلسل المنطقي",
    sec9Sub: "الخلاصة المنهجية لإنهاء النقاش",
    sec9Deduction: "سلسلة الاستنتاج المنطقي :",
    sec9Takeaway: "الخلاصة الواجب حفظها :",
    sec9Punchline: "العبارة الحاسمة لختام الحوار :",
    navPrevArg: "الشبهة السابقة",
    navNextArg: "الشبهة التالية",
    navBackSummary: "العودة إلى الفهرس",
    navEndManual: "نهاية الدليل (الرئيسية)",
    toastCopySuccess: "تم نسخ الرد السريع في الحافظة بنجاح !",
    quizBravo: "أحسنت ! إجابة صحيحة.",
    quizIncorrect: "إجابة خاطئة. حاول مجدداً !"
  },

  en: {
    brandBadge: "PRACTICAL MANUAL",
    brandTitle: "REFUTATION OF QURANISM",
    brandSubtitle: "How to expose and refute the Quranist sect and defend the Prophetic Sunnah",
    searchBtn: "Search",
    barbahariBtn: "Al-Barbahari",
    contactBtn: "Contact",
    legalBtn: "Sharing & License",
    summaryTitle: "Table of Contents",
    rubriquesCount: "12 sections",
    heroTag1: "Practical Refutation Manual",
    heroTag2: "Open Educational Resource",
    heroTitleMain: "Refutation",
    heroTitleSpan: "of Quranism",
    heroAuthor: "By Salah Eddine Ahmed — How to unmask and refute the Quranist sect: 10 major arguments examined and methodically refuted",
    heroDesc: "Step-by-step deconstruction of Quranist sophisms using logical rigor, pedagogical analogies, vocalized Arabic verses, and 30-second concise answers. Free to study and share in defense of truth.",
    btnStartArg1: "Start with Argument 1",
    btnSearchModal: "Search a topic / verse",
    btnContactAuthor: "Contact the author",
    sommaireTitle: "The 10 Major Arguments Decoded",
    sommaireBadge: "10 Ready-to-Use Factsheets",
    btnReadCard: "Read Factsheet",
    btnDownloadPdf: "Download original PDF",
    btnPrintCard: "Print / Save as PDF",
    goldenRuleHeader: "Golden Rule for debating a Quranist",
    goldenRuleTitle: "Never allow your interlocutor to shift the topic",
    goldenRuleDesc: "Most Quranist arguments rely on conceptual shifts: confusing the principle of the Sunnah (instituted by the Quran) with the historical transmission of later hadith collections.",
    goldenRuleStep1: "1. First establish what the Quran itself commands (Obedience, Judgment, Bayan, Exemplarity).",
    goldenRuleStep2: "2. Demonstrate that delegated prophetic authority never competes with Divine Sovereignty.",
    goldenRuleStep3: "3. Then methodically address the historical chain of transmission.",
    searchModalTitle: "Quick Search in the Manual",
    searchPlaceholder: "E.g., prayer, Surah An-Nahl verse 44, transmission, authority...",
    contactModalTitle: "Contact the Author & Feedback",
    contactAuthorBio: "Author of « How to unmask and refute the Quranist sect — Method, arguments, objections and answers ».",
    contactEmailBoxTitle: "Official Contact Email:",
    contactSuggestions: "You can send feedback, suggestions, or questions via email to ideoise@gmail.com.",
    legalModalTitle: "Terms of Sharing, Author & Privacy",
    legalSharingTitle: "Sharing & Educational Distribution Terms",
    legalSharingSubtitle: "Open Educational Sharing",
    legalSharingMainText: "This content may be freely shared and reproduced for personal, educational, and non-commercial purposes, provided source and author attribution are preserved.",
    legalAuthorizedUses: "Authorized uses: Downloading, printing, studying, and free sharing in study circles, classes, debates, and social media.",
    legalPrivacyTitle: "Technical Data & Privacy",
    legalPrivacySubtitle: "Privacy Policy aligned with actual website capabilities",
    legalPrivacyText: "The website requires no account creation and voluntarily collects no personal data via forms.",
    footerQuote: "« If you hear a man who is presented with an athar (tradition) reject it saying: Leave this and bring us the Quran, do not doubt that he is steeped in heresy. »",
    footerAuthorRef: "— Imam Al-Barbahari (Sharh As-Sunnah, item 135)",
    footerNotice: "Methodical refutation manual — Based on the reference work by Salah Eddine Ahmed.",
    footerNotice2: "Free content available for personal and educational sharing with source attribution.",
    portalWarningBadge: "WARNING OF THE EARLY SCHOLARS REGARDING THOSE WHO REJECT TRANSMISSION",
    portalTitle: "Statement of Imam Al-Barbahari (May Allah have mercy on him)",
    portalEnterBtn: "ACCESS THE REFUTATION MANUAL",
    portalAuthorBadge: "✍️ Imam Al-Barbahari (d. 329 AH)",
    portalSourceRef: "📖 Source: Sharh As-Sunnah (Point 135)",
    portalDisclaimer: "How to unmask and refute the Quranist sect • By Salah Eddine Ahmed • Open educational usage",
    argBadgeGiant: "ARGUMENT",
    btnDownloadOriginalPdf: "Download original PDF",
    btnPrintPage: "Print / Export PDF",
    formulaRetenir: "KEY FORMULA TO REMEMBER:",
    tocTitle: "Factsheet Outline",
    tocThesis: "Their thesis",
    tocLogical: "Logical core",
    tocPrinciple: "Central principle",
    tocQuranic: "Quranic architecture",
    tocAnalogies: "Analogies",
    tocResponses: "Ready answers",
    tocObjections: "Decrypted objections",
    tocQuiz: "Quiz",
    tocConclusion: "Conclusion",
    sec1Header: "1. THEIR THESIS & THE VERSES THEY MISINTERPRET",
    sec1Sub: "The Quranist position and its deconstruction",
    sec1CoranistTitle: "The Quranist Claim Unmasked",
    sec1VersesTitle: "Verses Cited by Quranists",
    sec1QuestionTitle: "The Real Doctrinal Question",
    sec2Header: "2. THE LOGICAL KNOT OF THE ISSUE",
    sec2Sub: "Dismantling conceptual confusions",
    sec2GeneralRule: "General rule of logic:",
    sec2ErrorAvoid: "The error to avoid:",
    sec3Header: "3. THE CENTRAL PRINCIPLE OF REFUTATION",
    sec3Sub: "The cornerstone argument",
    sec3FormalScheme: "FORMAL DEMONSTRATIVE SCHEME",
    sec3Explanation: "Theological & Rational Demonstration",
    sec3LogicalTest: "Decisive Logical Test:",
    sec4Header: "4. THE COMPLETE QURANIC ARCHITECTURE",
    sec4Sub: "Decisive verses establishing prophetic authority",
    sec4VersesRef: "Quranic Refutation Verses",
    sec4Consequence: "Unavoidable Doctrinal Consequence:",
    sec5Header: "5. PEDAGOGICAL ANALOGIES",
    sec5Sub: "To explain the reasoning in 30 seconds",
    sec6Header: "6. READY-TO-USE RESPONSES",
    sec6Sub: "Formats ready to recite or share",
    sec6QuickTitle: "30-Second Quick Response",
    btnCopyQuick: "Copy 30s response in 1 click",
    sec6DevTitle: "Comprehensive & Structured Response",
    sec7Header: "7. QURANIST OBJECTIONS & SYSTEMATIC ANSWERS",
    sec7Sub: "Anticipate every counter-argument",
    sec7ClickToggle: "Click any objection to view the methodical answer:",
    sec7DirectQuestions: "Direct framing questions:",
    sec8Header: "8. TEST YOUR UNDERSTANDING",
    sec8Sub: "Interactive Quiz on this Argument",
    sec8ValidateBtn: "Submit my answer",
    sec9Header: "9. LOGICAL CONCLUSION CHAIN",
    sec9Sub: "Methodical recap to conclude the debate",
    sec9Deduction: "Logical Deduction Chain:",
    sec9Takeaway: "Essential Takeaway:",
    sec9Punchline: "Final Debate Punchline:",
    navPrevArg: "Previous argument",
    navNextArg: "Next argument",
    navBackSummary: "Back to contents",
    navEndManual: "End of Manual (Home)",
    toastCopySuccess: "30s synthetic response copied to clipboard!",
    quizBravo: "Well done! Correct answer.",
    quizIncorrect: "Incorrect. Try again!"
  },

  es: {
    brandBadge: "MANUAL PRÁCTICO",
    brandTitle: "REFUTACIÓN DEL CORANISMO",
    brandSubtitle: "Cómo desenmascarar y refutar a la secta coranista y defender la Sunna",
    searchBtn: "Buscar",
    barbahariBtn: "Al-Barbahari",
    contactBtn: "Contacto",
    legalBtn: "Licencia y Compartir",
    summaryTitle: "Índice",
    rubriquesCount: "12 secciones",
    heroTag1: "Manual Práctico de Refutación",
    heroTag2: "Difusión Educativa Abierta",
    heroTitleMain: "Refutación",
    heroTitleSpan: "del Coranismo",
    heroAuthor: "Por Salah Eddine Ahmed — Cómo desenmascarar y refutar la secta coranista: 10 argumentos examinados y refutados metódicamente",
    heroDesc: "Deconstruye paso a paso los sofismas del coranismo con rigor lógico, analogías pedagógicas, versículos árabes vocalizados y respuestas sintéticas en 30 segundos.",
    btnStartArg1: "Comenzar con el Argumento 1",
    btnSearchModal: "Buscar tema / versículo",
    btnContactAuthor: "Contactar al autor",
    sommaireTitle: "Los 10 Grandes Argumentos Descifrados",
    sommaireBadge: "10 Fichas Listas para Usar",
    btnReadCard: "Ver ficha",
    btnDownloadPdf: "Descargar PDF original",
    btnPrintCard: "Imprimir / Guardar en PDF",
    goldenRuleHeader: "Regla de oro para debatir con un coranista",
    goldenRuleTitle: "Nunca dejes que el interlocutor desvíe el tema",
    goldenRuleDesc: "La mayoría de los argumentos coranistas se basan en confusiones: confundir el principio de la Sunna con la transmisión histórica de los libros posteriores.",
    goldenRuleStep1: "1. Establecer primero lo que ordena el Corán (Obediencia, Juicio, Bayan, Ejemplo).",
    goldenRuleStep2: "2. Demostrar que la autoridad profética delegada jamás compite con la Soberanía divina.",
    goldenRuleStep3: "3. Tratar luego metódicamente la cadena de transmisión histórica.",
    searchModalTitle: "Búsqueda Rápida en el Manual",
    searchPlaceholder: "Ej: oración, Surah An-Nahl v. 44, transmisión, autoridad...",
    contactModalTitle: "Contacto con el Autor",
    contactAuthorBio: "Autor de la obra « Cómo desenmascarar y refutar a la secta coranista ».",
    contactEmailBoxTitle: "Correo electrónico oficial de contacto:",
    contactSuggestions: "Puede enviar sus comentarios y preguntas por correo a ideoise@gmail.com.",
    legalModalTitle: "Condiciones de Compartir y Privacidad",
    legalSharingTitle: "Términos de Difusión Educativa",
    legalSharingSubtitle: "Compartir Abierto y Educativo",
    legalSharingMainText: "Este contenido puede ser compartido y reproducido gratuitamente para fines personales y educativos citando la fuente.",
    legalAuthorizedUses: "Usos autorizados: Descarga, impresión, lectura y difusión gratuita en círculos de estudio y redes sociales.",
    legalPrivacyTitle: "Datos Técnicos y Privacidad",
    legalPrivacySubtitle: "Política de Privacidad Transparente",
    legalPrivacyText: "El sitio no requiere cuentas ni recopila datos personales por formularios.",
    footerQuote: "« Si escuchas a un hombre que al citarle una tradición la rechaza diciendo: Déjanos esto y tráenos el Corán, no dudes de que está sumido en la herejía. »",
    footerAuthorRef: "— Imam Al-Barbahari (Sharh As-Sunnah, p. 135)",
    footerNotice: "Manual metódico basado en la obra de Salah Eddine Ahmed.",
    footerNotice2: "Contenido gratuito disponible para estudio con mención de la fuente.",
    portalWarningBadge: "ADVERTENCIA DE LOS PREDECESORES SOBRE QUIENES RECHAZAN LA TRANSMISIÓN",
    portalTitle: "Palabra del Imam Al-Barbahari (que Allah se apiade de él)",
    portalEnterBtn: "ACCEDER AL MANUAL DE REFUTACIÓN",
    portalAuthorBadge: "✍️ Imam Al-Barbahari (m. 329 H)",
    portalSourceRef: "📖 Fuente: Sharh As-Sunnah (Punto 135)",
    portalDisclaimer: "Cómo desenmascarar y refutar la secta coranista • Por Salah Eddine Ahmed",
    argBadgeGiant: "ARGUMENTO",
    btnDownloadOriginalPdf: "Descargar PDF original",
    btnPrintPage: "Imprimir / Exportar PDF",
    formulaRetenir: "FÓRMULA PARA RECORDAR:",
    tocTitle: "Índice de la ficha",
    tocThesis: "Su tesis",
    tocLogical: "Nudo lógico",
    tocPrinciple: "Principio central",
    tocQuranic: "Arquitectura coránica",
    tocAnalogies: "Analogías",
    tocResponses: "Respuestas listas",
    tocObjections: "Objeciones descifradas",
    tocQuiz: "Cuestionario",
    tocConclusion: "Conclusión",
    sec1Header: "1. SU TESIS Y LOS VERSÍCULOS QUE DESVÍAN",
    sec1Sub: "La postura coranista y su deconstrucción",
    sec1CoranistTitle: "La Tesis Coranista Desenmascarada",
    sec1VersesTitle: "Los Versículos que Invocan",
    sec1QuestionTitle: "La Verdadera Pregunta Doctrinal",
    sec2Header: "2. EL NUDO LÓGICO DEL PROBLEMA",
    sec2Sub: "Desmantelando confusiones conceptuales",
    sec2GeneralRule: "Regla general de lógica:",
    sec2ErrorAvoid: "El error a evitar:",
    sec3Header: "3. EL PRINCIPIO CENTRAL DE REFUTACIÓN",
    sec3Sub: "El argumento decisivo",
    sec3FormalScheme: "ESQUEMA FORMAL DEMOSTRATIVO",
    sec3Explanation: "Demostración Teológica y Racional",
    sec3LogicalTest: "Prueba Lógica Irrefutable:",
    sec4Header: "4. LA ARQUITECTURA CORÁNICA COMPLETA",
    sec4Sub: "Versículos decisivos de autoridad profética",
    sec4VersesRef: "Versículos Coránicos Refutatorios",
    sec4Consequence: "Consecuencia Doctrinal Ineludible:",
    sec5Header: "5. ANALOGÍAS PEDAGÓGICAS",
    sec5Sub: "Para entender el razonamiento en 30 segundos",
    sec6Header: "6. RESPUESTAS LISTAS PARA USAR",
    sec6Sub: "Formatos listos para formular o compartir",
    sec6QuickTitle: "Respuesta Rápida (30 Segundos)",
    btnCopyQuick: "Copiar respuesta 30s en 1 clic",
    sec6DevTitle: "Respuesta Desarrollada y Argumentada",
    sec7Header: "7. OBJECIONES CORANISTAS Y RESPUESTAS",
    sec7Sub: "Anticipe cada contraargumento",
    sec7ClickToggle: "Haga clic en una objeción para ver la respuesta metódica:",
    sec7DirectQuestions: "Preguntas de encuadre directo:",
    sec8Header: "8. EVALÚE SU COMPRENSIÓN",
    sec8Sub: "Cuestionario interactivo",
    sec8ValidateBtn: "Validar respuesta",
    sec9Header: "9. CONCLUSIÓN EN CADENA LÓGICA",
    sec9Sub: "Resumen metódico para cerrar el debate",
    sec9Deduction: "Cadena de Deducción Lógica:",
    sec9Takeaway: "Para Recordar Siempre:",
    sec9Punchline: "Frase Final de Debate:",
    navPrevArg: "Argumento anterior",
    navNextArg: "Argumento siguiente",
    navBackSummary: "Volver al índice",
    navEndManual: "Fin del Manual (Inicio)",
    toastCopySuccess: "¡Respuesta de 30s copiada al portapapeles!",
    quizBravo: "¡Excelente! Respuesta correcta.",
    quizIncorrect: "Incorrecto. ¡Inténtalo de nuevo!"
  },

  de: {
    brandBadge: "PRAKTISCHES HANDBUCH",
    brandTitle: "WIDERLEGUNG DES KORANISMUS",
    brandSubtitle: "Wie man die Sekte der Koranisten entlarvt und widerlegt",
    searchBtn: "Suchen",
    barbahariBtn: "Al-Barbahari",
    contactBtn: "Kontakt",
    legalBtn: "Teilen & Lizenz",
    summaryTitle: "Inhaltsverzeichnis",
    rubriquesCount: "12 Rubriken",
    heroTag1: "Praktisches Widerlegungshandbuch",
    heroTag2: "Freie Pädagogische Ressource",
    heroTitleMain: "Widerlegung",
    heroTitleSpan: "des Koranismus",
    heroAuthor: "Von Salah Eddine Ahmed — Die Sekte der Koranisten entlarven und widerlegen: 10 Kernargumente methodisch geprüft",
    heroDesc: "Schrittweise Dekonstruktion koranistischer Trugschlüsse mit logischer Strenge, pädagogischen Analogien, vokalisierten arabischen Versen und prägnanten 30-Sekunden-Antworten.",
    btnStartArg1: "Mit Argument 1 beginnen",
    btnSearchModal: "Thema / Vers suchen",
    btnContactAuthor: "Autor kontaktieren",
    sommaireTitle: "Die 10 Kernargumente entschlüsselt",
    sommaireBadge: "10 einsatzbereite Dossiers",
    btnReadCard: "Dossier lesen",
    btnDownloadPdf: "Original-PDF herunterladen",
    btnPrintCard: "Drucken / Als PDF speichern",
    goldenRuleHeader: "Goldene Regel für die Debatte mit einem Koranisten",
    goldenRuleTitle: "Lassen Sie den Gesprächspartner niemals das Thema verlagern",
    goldenRuleDesc: "Die meisten koranistischen Argumente beruhen auf begrifflichen Verschiebungen: Verwechslung des Prinzips der Sunnah mit der historischen Überlieferung späterer Sammlungen.",
    goldenRuleStep1: "1. Zuerst feststellen, was der Koran selbst befiehlt (Gehorsam, Urteil, Bayan, Vorbild).",
    goldenRuleStep2: "2. Zeigen, dass delegierte prophetische Autorität niemals mit der göttlichen Souveränität konkurriert.",
    goldenRuleStep3: "3. Danach methodisch die historische Überlieferungskette behandeln.",
    searchModalTitle: "Schnellsuche im Handbuch",
    searchPlaceholder: "Z.B. Gebet, Sure An-Nahl Vers 44, Überlieferung, Autorität...",
    contactModalTitle: "Autor kontaktieren & Feedback",
    contactAuthorBio: "Autor des Werkes « Die Sekte der Koranisten entlarven und widerlegen ».",
    contactEmailBoxTitle: "Offizielle Kontakt-E-Mail:",
    contactSuggestions: "Senden Sie Feedback oder Fragen per E-Mail an ideoise@gmail.com.",
    legalModalTitle: "Bedingungen für Teilen, Autor & Datenschutz",
    legalSharingTitle: "Bedingungen für pädagogische Weitergabe",
    legalSharingSubtitle: "Offene pädagogische Weitergabe",
    legalSharingMainText: "Dieser Inhalt darf für persönliche und Bildungszwecke unter Nennung der Quelle frei geteilt werden.",
    legalAuthorizedUses: "Erlaubte Nutzung: Herunterladen, Drucken, Lesen und freies Teilen in Studienkreisen und sozialen Medien.",
    legalPrivacyTitle: "Technische Daten & Datenschutz",
    legalPrivacySubtitle: "Datenschutzerklärung entsprechend tatsächlicher Funktionalität",
    legalPrivacyText: "Die Website erfordert keine Konten und sammelt keine persönlichen Daten.",
    footerQuote: "« Wenn du hörst, dass ein Mann einen Athar (Überlieferung) ablehnt und sagt: Lass das und bring uns den Koran, so zweifle nicht daran, dass er von Häresie ergriffen ist. »",
    footerAuthorRef: "— Imam Al-Barbahari (Scharh As-Sunnah, Pkt. 135)",
    footerNotice: "Methodisches Handbuch — Basierend auf dem Referenzwerk von Salah Eddine Ahmed.",
    footerNotice2: "Freier Inhalt zur persönlichen und pädagogischen Nutzung mit Quellenangabe.",
    portalWarningBadge: "WARNUNG DER FRÜHEN GELEHRTEN VOR DER ABLEHNUNG DER ÜBERLIEFERUNG",
    portalTitle: "Wort von Imam Al-Barbahari (möge Allah ihm barmherzig sein)",
    portalEnterBtn: "ZUM WIDERLEGUNGSHANDBUCH",
    portalAuthorBadge: "✍️ Imam Al-Barbahari (gest. 329 n.H.)",
    portalSourceRef: "📖 Quelle: Scharh As-Sunnah (Punkt 135)",
    portalDisclaimer: "Die Sekte der Koranisten entlarven und widerlegen • Von Salah Eddine Ahmed",
    argBadgeGiant: "ARGUMENT",
    btnDownloadOriginalPdf: "Original-PDF herunterladen",
    btnPrintPage: "Drucken / PDF exportieren",
    formulaRetenir: "FORMEL ZUM MERKEN:",
    tocTitle: "Gliederung",
    tocThesis: "Ihre These",
    tocLogical: "Logischer Kern",
    tocPrinciple: "Zentrales Prinzip",
    tocQuranic: "Koranische Architektur",
    tocAnalogies: "Analogien",
    tocResponses: "Fertige Antworten",
    tocObjections: "Entschlüsselte Einwände",
    tocQuiz: "Quiz",
    tocConclusion: "Fazit",
    sec1Header: "1. IHRE THESE & DIE FEHLINTERPRETIERTEN VERSE",
    sec1Sub: "Die koranistische Position und ihre Dekonstruktion",
    sec1CoranistTitle: "Die entlarvte koranistische Behauptung",
    sec1VersesTitle: "Von Koranisten angeführte Verse",
    sec1QuestionTitle: "Die eigentliche doktrinäre Frage",
    sec2Header: "2. DER LOGISCHE KNOTEN DES PROBLEMS",
    sec2Sub: "Beseitigung begrifflicher Verwirrungen",
    sec2GeneralRule: "Allgemeine Logikregel:",
    sec2ErrorAvoid: "Zu vermeidender Fehler:",
    sec3Header: "3. DAS ZENTRALE WIDERLEGUNGSPRINZIP",
    sec3Sub: "Das entscheidende Hauptargument",
    sec3FormalScheme: "FORMALES BEWEISSCHEMA",
    sec3Explanation: "Theologische & Rationale Demonstration",
    sec3LogicalTest: "Unwiderlegbarer logischer Test:",
    sec4Header: "4. DIE GESAMTE KORANISCHE ARCHITEKTUR",
    sec4Sub: "Entscheidende Verse zur prophetischen Autorität",
    sec4VersesRef: "Widerlegende koranische Verse",
    sec4Consequence: "Zwingende doktrinäre Schlussfolgerung:",
    sec5Header: "5. PÄDAGOGISCHE ANALOGIEN",
    sec5Sub: "Um den Gedankengang in 30 Sekunden verständlich zu machen",
    sec6Header: "6. EINSATZBEREITE ANTWORTEN",
    sec6Sub: "Formate zum Formulieren oder Teilen",
    sec6QuickTitle: "Schnellantwort (30 Sekunden)",
    btnCopyQuick: "30s-Antwort mit 1 Klick kopieren",
    sec6DevTitle: "Ausführliche und begründete Antwort",
    sec7Header: "7. KORANISTISCHE EINWÄNDE & METHODISCHE ANTWORTEN",
    sec7Sub: "Antizipieren Sie jedes Gegenargument",
    sec7ClickToggle: "Klicken Sie auf einen Einwand für die methodische Antwort:",
    sec7DirectQuestions: "Direkte Leitfragen:",
    sec8Header: "8. TESTEN SIE IHR VERSTÄNDNIS",
    sec8Sub: "Interaktives Quiz",
    sec8ValidateBtn: "Antwort überprüfen",
    sec9Header: "9. FAZIT IN LOGISCHER KETTE",
    sec9Sub: "Methodische Zusammenfassung zum Debattenabschluss",
    sec9Deduction: "Logische Deduktionskette:",
    sec9Takeaway: "Unbedingt merken:",
    sec9Punchline: "Schlussformel für Debatten:",
    navPrevArg: "Vorheriges Argument",
    navNextArg: "Nächstes Argument",
    navBackSummary: "Zurück zur Übersicht",
    navEndManual: "Ende des Handbuchs (Startseite)",
    toastCopySuccess: "30s-Antwort in die Zwischenablage kopiert!",
    quizBravo: "Ausgezeichnet! Richtige Antwort.",
    quizIncorrect: "Falsch. Versuchen Sie es erneut!"
  },

  it: {
    brandBadge: "MANUALE PRATICO",
    brandTitle: "CONFUTAZIONE DEL CORANISMO",
    brandSubtitle: "Come smascherare e confutare la setta dei coranisti e difendere la Sunna",
    searchBtn: "Cerca",
    barbahariBtn: "Al-Barbahari",
    contactBtn: "Contatto",
    legalBtn: "Condivisione & Licenza",
    summaryTitle: "Indice",
    rubriquesCount: "12 sezioni",
    heroTag1: "Manuale Pratico di Confutazione",
    heroTag2: "Diffusione Pedagogica Aperta",
    heroTitleMain: "Confutazione",
    heroTitleSpan: "del Coranismo",
    heroAuthor: "Di Salah Eddine Ahmed — Come smascherare e confutare la setta dei coranisti: 10 argomenti esaminati e confutati metodicamente",
    heroDesc: "Decostruisci passo dopo passo i sofismi del coranismo con rigore logico, analogie pedagogiche, versetti arabi vocalizzati e risposte sintetiche in 30 secondi.",
    btnStartArg1: "Inizia con l'Argomento 1",
    btnSearchModal: "Cerca argomento / versetto",
    btnContactAuthor: "Contatta l'autore",
    sommaireTitle: "I 10 Grandi Argomenti Decodificati",
    sommaireBadge: "10 Schede Pronte all'Uso",
    btnReadCard: "Leggi scheda",
    btnDownloadPdf: "Scarica PDF originale",
    btnPrintCard: "Stampa / Salva in PDF",
    goldenRuleHeader: "Regola d'oro per dibattere con un coranista",
    goldenRuleTitle: "Non lasciare mai che l'interlocutore sposti il tema",
    goldenRuleDesc: "La maggior parte degli argomenti coranisti si basa su slittamenti: confondere il principio della Sunna con la trasmissione storica delle raccolte posteriori.",
    goldenRuleStep1: "1. Stabilire prima cosa ordina il Corano (Obbedienza, Giudizio, Bayan, Esempio).",
    goldenRuleStep2: "2. Dimostrare che l'autorità profetica delegata non compete mai con la Sovranità divina.",
    goldenRuleStep3: "3. Trattare poi metodicamente la catena di trasmissione storica.",
    searchModalTitle: "Ricerca Rapida nel Manuale",
    searchPlaceholder: "Es: preghiera, Sura An-Nahl v. 44, trasmissione, autorità...",
    contactModalTitle: "Contatto Autore & Feedback",
    contactAuthorBio: "Autore dell'opera « Come smascherare e confutare la setta dei coranisti ».",
    contactEmailBoxTitle: "Email di contatto ufficiale:",
    contactSuggestions: "Puoi inviare feedback o domande via email a ideoise@gmail.com.",
    legalModalTitle: "Condizioni di Condivisione e Privacy",
    legalSharingTitle: "Termini di Condivisione Pedagogica",
    legalSharingSubtitle: "Diffusione e Condivisione Aperta",
    legalSharingMainText: "Questo contenuto può essere condiviso gratuitamente a fini personali ed educativi citando la fonte.",
    legalAuthorizedUses: "Usi autorizzati: Download, stampa, lettura e condivisione gratuita in lezioni e social media.",
    legalPrivacyTitle: "Dati Tecnici & Privacy",
    legalPrivacySubtitle: "Informativa sulla Privacy",
    legalPrivacyText: "Il sito non richiede account e non raccoglie dati personali tramite moduli.",
    footerQuote: "« Se senti un uomo a cui viene citato un athar rifiutarlo dicendo: Lascia questo e portaci il Corano, non dubitare che sia intriso di eresia. »",
    footerAuthorRef: "— Imam Al-Barbahari (Sharh As-Sunnah, p. 135)",
    footerNotice: "Manuale metodico basato sull'opera di Salah Eddine Ahmed.",
    footerNotice2: "Contenuto gratuito per studio con menzione della fonte.",
    portalWarningBadge: "AVVERTIMENTO DEI PREDECESSORI SU CHI RIFIUTA LA TRASMISSIONE",
    portalTitle: "Parola dell'Imam Al-Barbahari (che Allah abbia misericordia di lui)",
    portalEnterBtn: "ACCEDI AL MANUALE DI CONFUTAZIONE",
    portalAuthorBadge: "✍️ Imam Al-Barbahari (m. 329 E)",
    portalSourceRef: "📖 Fonte: Sharh As-Sunnah (Punto 135)",
    portalDisclaimer: "Come smascherare e confutare la setta dei coranisti • Di Salah Eddine Ahmed",
    argBadgeGiant: "ARGOMENTO",
    btnDownloadOriginalPdf: "Scarica PDF originale",
    btnPrintPage: "Stampa / Esporta PDF",
    formulaRetenir: "FORMULA DA RICORDARE:",
    tocTitle: "Indice della scheda",
    tocThesis: "La loro tesi",
    tocLogical: "Nodo logico",
    tocPrinciple: "Principio centrale",
    tocQuranic: "Architettura coranica",
    tocAnalogies: "Analogie",
    tocResponses: "Risposte pronte",
    tocObjections: "Obiezioni decifrate",
    tocQuiz: "Quiz",
    tocConclusion: "Conclusione",
    sec1Header: "1. LA LORO TESI E I VERSETTI CHE TRAVISANO",
    sec1Sub: "La posizione coranista e la sua decostruzione",
    sec1CoranistTitle: "La Tesi Coranista Smascherata",
    sec1VersesTitle: "I Versetti Invocati",
    sec1QuestionTitle: "La Vera Domanda Dottrinale",
    sec2Header: "2. IL NODO LOGICO DEL PROBLEMA",
    sec2Sub: "Smantellare le confusioni concettuali",
    sec2GeneralRule: "Regola generale di logica:",
    sec2ErrorAvoid: "L'errore da evitare:",
    sec3Header: "3. IL PRINCIPIO CENTRALE DI CONFUTAZIONE",
    sec3Sub: "L'argomento cardine",
    sec3FormalScheme: "SCHEMA FORMALE DIMOSTRATIVO",
    sec3Explanation: "Dimostrazione Teologica e Razionale",
    sec3LogicalTest: "Test Logico Decisivo:",
    sec4Header: "4. L'ARCHITETTURA CORANICA COMPLETA",
    sec4Sub: "Versetti decisivi sull'autorità profetica",
    sec4VersesRef: "Versetti Coranici di Confutazione",
    sec4Consequence: "Conseguenza Dottrinale Inevitabile:",
    sec5Header: "5. ANALOGIE PEDAGOGICHE",
    sec5Sub: "Per far comprendere il ragionamento in 30 secondi",
    sec6Header: "6. RISPOSTE PRONTE ALL'USO",
    sec6Sub: "Formati pronti da recitare o condividere",
    sec6QuickTitle: "Risposta Rapida (30 Secondi)",
    btnCopyQuick: "Copia risposta 30s in 1 clic",
    sec6DevTitle: "Risposta Approfondita e Argomentata",
    sec7Header: "7. OBIEZIONI CORANISTE E RISPOSTE",
    sec7Sub: "Anticipa ogni controargomento",
    sec7ClickToggle: "Clicca su un'obiezione per visualizzare la risposta metodica:",
    sec7DirectQuestions: "Domande dirette di inquadramento:",
    sec8Header: "8. METTI ALLA PROVA LA TUA COMPRENSIONE",
    sec8Sub: "Quiz interattivo",
    sec8ValidateBtn: "Verifica risposta",
    sec9Header: "9. CONCLUSIONE IN CATENA LOGICA",
    sec9Sub: "Riepilogo metodico per chiudere il dibattito",
    sec9Deduction: "Catena di Deduzione Logica:",
    sec9Takeaway: "Da Ricordare Assolutamente:",
    sec9Punchline: "Frase Finale di Dibattito:",
    navPrevArg: "Argomento precedente",
    navNextArg: "Argomento successivo",
    navBackSummary: "Torna all'indice",
    navEndManual: "Fine del Manuale (Home)",
    toastCopySuccess: "Risposta sintetica di 30s copiata negli appunti!",
    quizBravo: "Ottimo! Risposta corretta.",
    quizIncorrect: "Errato. Riprova!"
  },

  pt: {
    brandBadge: "MANUAL PRÁTICO",
    brandTitle: "REFUTAÇÃO DO QURANISMO",
    brandSubtitle: "Como desmascarar e refutar a seita dos coranistas e defender a Sunna",
    searchBtn: "Pesquisar",
    barbahariBtn: "Al-Barbahari",
    contactBtn: "Contacto",
    legalBtn: "Partilha & Licença",
    summaryTitle: "Índice",
    rubriquesCount: "12 secções",
    heroTag1: "Manual Prático de Refutação",
    heroTag2: "Difusão Pedagógica Aberta",
    heroTitleMain: "Refutação",
    heroTitleSpan: "do Quranismo",
    heroAuthor: "Por Salah Eddine Ahmed — Como desmascarar e refutar a seita dos coranistas: 10 argumentos examinados e refutados metodicamente",
    heroDesc: "Desconstrua passo a passo os sofismas do coranismo com rigor lógico, analogias pedagógicas, versículos árabes vocalizados e respostas sintéticas em 30 segundos.",
    btnStartArg1: "Começar pelo Argumento 1",
    btnSearchModal: "Pesquisar tema / versículo",
    btnContactAuthor: "Contactar o autor",
    sommaireTitle: "Os 10 Grandes Argumentos Decifrados",
    sommaireBadge: "10 Fichas Prontas a Usar",
    btnReadCard: "Ler ficha",
    btnDownloadPdf: "Descarregar PDF original",
    btnPrintCard: "Imprimir / Guardar em PDF",
    goldenRuleHeader: "Regra de ouro para debater com um coranista",
    goldenRuleTitle: "Nunca permita que o interlocutor mude o tema",
    goldenRuleDesc: "A maioria dos argumentos coranistas baseia-se em confusões: confundir o princípio da Sunna com a transmissão histórica das compilações posteriores.",
    goldenRuleStep1: "1. Estabelecer primeiro o que o Alcorão ordena (Obediência, Julgamento, Bayan, Exemplo).",
    goldenRuleStep2: "2. Demonstrar que a autoridade profética delegada jamais compete com a Soberania divina.",
    goldenRuleStep3: "3. Tratar depois metodicamente a cadeia de transmissão histórica.",
    searchModalTitle: "Pesquisa Rápida no Manual",
    searchPlaceholder: "Ex: oração, Surah An-Nahl v. 44, transmissão, autoridade...",
    contactModalTitle: "Contacto com o Autor & Feedback",
    contactAuthorBio: "Autor da obra « Como desmascarar e refutar a seita dos coranistas ».",
    contactEmailBoxTitle: "E-mail de contacto oficial:",
    contactSuggestions: "Pode enviar comentários e perguntas por e-mail para ideoise@gmail.com.",
    legalModalTitle: "Termos de Partilha e Privacidade",
    legalSharingTitle: "Termos de Difusão Pedagógica",
    legalSharingSubtitle: "Partilha Pedagógica Aberta",
    legalSharingMainText: "Este conteúdo pode ser partilhado gratuitamente para fins pessoais e educativos com citação da fonte.",
    legalAuthorizedUses: "Usos autorizados: Download, impressão, estudo e partilha em círculos de estudo e redes sociais.",
    legalPrivacyTitle: "Dados Técnicos & Privacidade",
    legalPrivacySubtitle: "Política de Privacidade",
    legalPrivacyText: "O site não exige registo nem recolhe dados pessoais por formulários.",
    footerQuote: "« Se ouvires um homem a quem se cita um athar rejeitá-lo dizendo: Deixa isso e traz-nos o Alcorão, não duvides de que está impregnado de heresia. »",
    footerAuthorRef: "— Imam Al-Barbahari (Sharh As-Sunnah, p. 135)",
    footerNotice: "Manual metódico baseado na obra de Salah Eddine Ahmed.",
    footerNotice2: "Conteúdo livre para estudo com menção da fonte.",
    portalWarningBadge: "AVISO DOS PREDECESSORES SOBRE QUEM REJEITA A TRANSMISSÃO",
    portalTitle: "Palavra do Imam Al-Barbahari (que Allah tenha misericórdia dele)",
    portalEnterBtn: "ACEDER AO MANUAL DE REFUTAÇÃO",
    portalAuthorBadge: "✍️ Imam Al-Barbahari (m. 329 H)",
    portalSourceRef: "📖 Fonte: Sharh As-Sunnah (Ponto 135)",
    portalDisclaimer: "Como desmascarar e refutar a seita dos coranistas • Por Salah Eddine Ahmed",
    argBadgeGiant: "ARGUMENTO",
    btnDownloadOriginalPdf: "Descarregar PDF original",
    btnPrintPage: "Imprimir / Exportar PDF",
    formulaRetenir: "FÓRMULA A RETER:",
    tocTitle: "Índice da ficha",
    tocThesis: "A sua tese",
    tocLogical: "Nó lógico",
    tocPrinciple: "Princípio central",
    tocQuranic: "Arquitetura alcorânica",
    tocAnalogies: "Analogias",
    tocResponses: "Respostas prontas",
    tocObjections: "Objeções decifradas",
    tocQuiz: "Quiz",
    tocConclusion: "Conclusão",
    sec1Header: "1. A SUA TESE E OS VERSÍCULOS QUE DETURPAM",
    sec1Sub: "A posição coranista e a sua desconstrução",
    sec1CoranistTitle: "A Tese Coranista Desmascarada",
    sec1VersesTitle: "Versículos Invocados",
    sec1QuestionTitle: "A Verdadeira Questão Doutrinária",
    sec2Header: "2. O NÓ LÓGICO DO PROBLEMA",
    sec2Sub: "Desmantelando confusões conceituais",
    sec2GeneralRule: "Regra geral de lógica:",
    sec2ErrorAvoid: "O erro a evitar:",
    sec3Header: "3. O PRINCÍPIO CENTRAL DE REFUTAÇÃO",
    sec3Sub: "O argumento fulcral",
    sec3FormalScheme: "ESQUEMA FORMAL DEMONSTRATIVO",
    sec3Explanation: "Demonstração Teológica e Racional",
    sec3LogicalTest: "Teste Lógico Decisivo:",
    sec4Header: "4. A ARQUITETURA ALCORÂNICA COMPLETA",
    sec4Sub: "Versículos decisivos sobre a autoridade profética",
    sec4VersesRef: "Versículos Alcorânicos Refutatórios",
    sec4Consequence: "Consequência Doutrinária Inevitável:",
    sec5Header: "5. ANALOGIAS PEDAGÓGICAS",
    sec5Sub: "Para fazer compreender o raciocínio em 30 segundos",
    sec6Header: "6. RESPOSTAS PRONTAS A USAR",
    sec6Sub: "Formatos prontos a usar ou partilhar",
    sec6QuickTitle: "Resposta Rápida (30 Segundos)",
    btnCopyQuick: "Copiar resposta 30s com 1 clique",
    sec6DevTitle: "Resposta Desenvolvida e Argumentada",
    sec7Header: "7. OBJEÇÕES CORANISTAS E RESPOSTAS",
    sec7Sub: "Antecipe cada contra-argumento",
    sec7ClickToggle: "Clique numa objeção para ver a resposta metódica:",
    sec7DirectQuestions: "Perguntas de enquadramento direto:",
    sec8Header: "8. TESTE A SUA COMPREENSÃO",
    sec8Sub: "Quiz interativo",
    sec8ValidateBtn: "Validar resposta",
    sec9Header: "9. CONCLUSÃO EM CADEIA LÓGICA",
    sec9Sub: "Resumo metódico para encerrar o debate",
    sec9Deduction: "Cadeia de Dedução Lógica:",
    sec9Takeaway: "A Reter Absolutamente:",
    sec9Punchline: "Frase Final de Debate:",
    navPrevArg: "Argumento anterior",
    navNextArg: "Argumento seguinte",
    navBackSummary: "Voltar ao índice",
    navEndManual: "Fim do Manual (Início)",
    toastCopySuccess: "Resposta sintética de 30s copiada para a área de transferência!",
    quizBravo: "Parabéns! Resposta correta.",
    quizIncorrect: "Incorreto. Tente novamente!"
  },

  ur: {
    brandBadge: "عملی رہنما",
    brandTitle: "فتنہ انکار حدیث کا رد",
    brandSubtitle: "منکرین حدیث کے شبہات کا علمی و منطقی محاسبہ اور سنت نبویہ کا دفاع",
    searchBtn: "تلاش",
    barbahariBtn: "البربہاری",
    contactBtn: "رابطہ",
    legalBtn: "اشاعت و اجازت",
    summaryTitle: "فہرست مضامین",
    rubriquesCount: "12 ابواب",
    heroTag1: "منہجی و عملی رد کا رہنما",
    heroTag2: "مفت تعلیمی و دعوتی اشاعت",
    heroTitleMain: "فتنہ انکار حدیث",
    heroTitleSpan: "کا علمی محاسبہ",
    heroAuthor: "بقلم صلاح الدین احمد — منکرین حدیث کے 10 بنیادی شبہات کا مدلل اور مسکت رد",
    heroDesc: "منکرین حدیث کی گمراہیوں اور مغالطوں کا ٹھوس منطقی دلائل، فہم سلف، اعراب شدہ قرآنی آیات اور 30 سیکنڈ کے مسکت جوابات کے ساتھ مرحلہ وار جائزہ۔ حق کے دفاع کے لیے مطالعہ اور نشر کریں۔",
    btnStartArg1: "پہلے شبہے سے آغاز کریں",
    btnSearchModal: "موضوع / آیت تلاش کریں",
    btnContactAuthor: "مصنف سے رابطہ",
    sommaireTitle: "منکرین حدیث کے 10 بڑے شبہات کا تجزیہ",
    sommaireBadge: "10 جامع اور تیار علمی فائیلز",
    btnReadCard: "کارڈ ملاحظہ کریں",
    btnDownloadPdf: "اصل PDF ڈاؤن لوڈ کریں",
    btnPrintCard: "پرنٹ / PDF محفوظ کریں",
    goldenRuleHeader: "منکرین حدیث سے گفتگو کا سنہری اصول",
    goldenRuleTitle: "مخاطب کو کبھی موضوع سے بھٹکنے نہ دیں",
    goldenRuleDesc: "منکرین حدیث کے اکثر شبہات کا دارومدار بنیادی خلط مبحث پر ہوتا ہے: قرآن کے ذریعے ثابت شدہ 'حجیت سنت' کو بعد کی کتب حدیث کی تاریخی تدوین سے خلط ملط کر دینا۔",
    goldenRuleStep1: "1. پہلے قرآن سے ثابت کریں کہ اللہ نے رسول کی اطاعت، فیصلے، بیان اور نمونے کا کیا حکم دیا ہے۔",
    goldenRuleStep2: "2. واضح کریں کہ رسول اللہ ﷺ کا تفویض کردہ اختیار الٰہی حاکمیت کے مدمقابل نہیں بلکہ اسی کا تقاضا ہے۔",
    goldenRuleStep3: "3. اس کے بعد تاریخی اسناد اور تدوین حدیث کے سوال کا سائنسی و علمی جواب دیں۔",
    searchModalTitle: "رہنما میں فوری تلاش",
    searchPlaceholder: "مثلاً: نماز، سورۃ النحل آیت 44، روایت، حجیت سنت...",
    contactModalTitle: "مصنف سے رابطہ اور تجاویز",
    contactAuthorBio: "کتاب « منکرین حدیث کے شبہات کا رد — منہج، دلائل اور جوابات » کے مصنف۔",
    contactEmailBoxTitle: "رسمی رابطہ ای میل :",
    contactSuggestions: "آپ اپنی آراء اور تجاویز ideoise@gmail.com پر ای میل کر سکتے ہیں۔",
    legalModalTitle: "اشاعت، حقوق اور رازداری کے ضوابط",
    legalSharingTitle: "تعلیمی اشاعت و ترسیل کی شرائط",
    legalSharingSubtitle: "کھلی تعلیمی و دینی اشاعت",
    legalSharingMainText: "یہ مواد ذاتی اور تعلیمی مقاصد کے لیے بلا معاوضہ شیئر اور پرنٹ کیا جا سکتا ہے، بشرطیکہ مصنف اور ماخذ کا حوالہ برقرار رکھا جائے۔",
    legalAuthorizedUses: "مجاز استعمال: ڈاؤن لوڈ، پرنٹنگ، مطالعہ اور درسی حلقوں، مباحثوں اور سوشل میڈیا پر مفت نشر کرنا۔",
    legalPrivacyTitle: "تکنیکی ڈیٹا اور رازداری",
    legalPrivacySubtitle: "رازداری کی شفاف پالیسی",
    legalPrivacyText: "یہ سائٹ کوئی اکاؤنٹ یا ذاتی ڈیٹا جمع نہیں کرتی۔",
    footerQuote: "« جب تم کسی شخص کو دیکھو کہ اس کے سامنے کوئی حدیث یا اثر پیش کیا جائے اور وہ کہے: اسے چھوڑو اور ہمیں قرآن سے بتاؤ، تو جان لو کہ وہ شخص گمراہی میں مبتلا ہے۔ »",
    footerAuthorRef: "— امام البربہاری رحمہ اللہ (شرح السنۃ، فقره 135)",
    footerNotice: "صلاح الدین احمد کی کتاب پر مبنی منہجی رد۔",
    footerNotice2: "حوالے کے ساتھ مطالعہ اور دعوت کے لیے بلا معاوضہ دستیاب۔",
    portalWarningBadge: "سلف صالحین کی منکرین حدیث اور روایات کے طاعنین سے تنبیہ",
    portalTitle: "امام البربہاری رحمہ اللہ کا بصیرت افروز قول",
    portalEnterBtn: "رد کے رہنما میں داخل ہوں",
    portalAuthorBadge: "✍️ امام البربہاری (وفات 329 ھ)",
    portalSourceRef: "📖 ماخذ: شرح السنہ (فقرہ 135)",
    portalDisclaimer: "منکرین حدیث کے شبہات کا رد • بقلم صلاح الدین احمد",
    argBadgeGiant: "شبہ نمبر",
    btnDownloadOriginalPdf: "اصل PDF ڈاؤن لوڈ کریں",
    btnPrintPage: "پرنٹ / PDF برآمد کریں",
    formulaRetenir: "یاد رکھنے کا بنیادی قاعدہ :",
    tocTitle: "مندرجات کارڈ",
    tocThesis: "ان کا دعویٰ",
    tocLogical: "منطقی گرہ",
    tocPrinciple: "بنیادی اصول",
    tocQuranic: "قرآنی دلائل",
    tocAnalogies: "تمثیلات",
    tocResponses: "تیار جوابات",
    tocObjections: "اعتراضات کا حل",
    tocQuiz: "فہم کا امتحان",
    tocConclusion: "منطقی نتیجہ",
    sec1Header: "1. ان کا شبہ اور وہ آیات جن کا وہ غلط مفہوم لیتے ہیں",
    sec1Sub: "منکرین حدیث کا موقف اور اس کی حقیقت",
    sec1CoranistTitle: "منکرین حدیث کا اصل دعویٰ",
    sec1VersesTitle: "وہ قرآنی آیات جن کا وہ سہارا لیتے ہیں",
    sec1QuestionTitle: "اصل ایمانی و فکری سوال",
    sec2Header: "2. مسئلے کی منطقی گرہ اور مغالطے کا ازالہ",
    sec2Sub: "مفاہیم کے خلط ملط کو الگ کرنا",
    sec2GeneralRule: "عام منطقی قاعدہ :",
    sec2ErrorAvoid: "وہ غلطی جس سے بچنا لازمی ہے :",
    sec3Header: "3. رد کا بنیادی اور محکم اصول",
    sec3Sub: "مسکت اور فیصلہ کن دلیل",
    sec3FormalScheme: "باقاعدہ استدلالی خاکہ",
    sec3Explanation: "عقلی اور شرعی ثبوت",
    sec3LogicalTest: "حتمی منطقی امتحان :",
    sec4Header: "4. حجیت سنت کی مکمل قرآنی عمارت",
    sec4Sub: "رسول اللہ ﷺ کے اختیارات پر قطعی قرآنی آیات",
    sec4VersesRef: "رد کرنے والی قرآنی آیات",
    sec4Consequence: "ناگزیر شرعی نتیجہ :",
    sec5Header: "5. فہم کے قریب لانے والی تمثیلات",
    sec5Sub: "30 سیکنڈ میں بات سمجھانے کے لیے",
    sec6Header: "6. بر وقت استعمال کے لیے تیار جوابات",
    sec6Sub: "گفتگو یا شیئر کرنے کے لیے فوری فارمیٹس",
    sec6QuickTitle: "فوری جواب (30 سیکنڈ)",
    btnCopyQuick: "30 سیکنڈ کا جواب ایک کلک پر کاپی کریں",
    sec6DevTitle: "مفصل اور مدلل جواب",
    sec7Header: "7. منکرین کے متوقع اعتراضات اور ان کے جوابات",
    sec7Sub: "ہر جوابی اعتراض کا پہلے سے مسکت توڑ",
    sec7ClickToggle: "کسی بھی اعتراض پر کلک کر کے اس کا منہجی جواب دیکھیں :",
    sec7DirectQuestions: "براہ راست الزامی سوالات :",
    sec8Header: "8. اپنی تفہیم کا امتحان لیں",
    sec8Sub: "اس شبہے پر تفاعلی کوئز",
    sec8ValidateBtn: "جواب تصدیق کریں",
    sec9Header: "9. منطقی استنتاج اور نتیجہ",
    sec9Sub: "بحث سمیٹنے کے لیے حتمی خلاصہ",
    sec9Deduction: "منطقی نتائج کی کڑی :",
    sec9Takeaway: "لازمی یاد رکھنے کی بات :",
    sec9Punchline: "مباحثے کا اختتامی جملہ :",
    navPrevArg: "پچھلا شبہ",
    navNextArg: "اگلا شبہ",
    navBackSummary: "فہرست پر واپس",
    navEndManual: "رہنما کا اختتام (مرکزی صفحہ)",
    toastCopySuccess: "30 سیکنڈ کا جامع جواب کلپ بورڈ پر کاپی ہو گیا!",
    quizBravo: "شاباش! درست جواب۔",
    quizIncorrect: "غلط جواب۔ دوبارہ کوشش کریں!"
  },

  ta: {
    brandBadge: "நடைமுறை வழிகாட்டி",
    brandTitle: "குர்ஆனிசத்தின் மறுப்பு",
    brandSubtitle: "ஹதீஸ் மறுப்பாளர்களின் வாதங்களை அம்பலப்படுத்தி சுன்னாவை நிலைநாட்டுதல்",
    searchBtn: "தேடுக",
    barbahariBtn: "அல்-பர்பஹாரி",
    contactBtn: "தொடர்பு",
    legalBtn: "பகிர்வு & உரிமம்",
    summaryTitle: "பொருளடக்கம்",
    rubriquesCount: "12 பகுதிகள்",
    heroTag1: "நடைமுறை மறுப்பு வழிகாட்டி",
    heroTag2: "இலவச கல்விப் பகிர்வு",
    heroTitleMain: "குர்ஆனிசத்தின்",
    heroTitleSpan: "ஆதாரபூர்வ மறுப்பு",
    heroAuthor: "எழுதியவர்: ஸலாஹ் எத்தீன் அஹ்மத் — ஹதீஸ் மறுப்பாளர்களின் 10 முக்கிய வாதங்களுக்கான முறைப்படியான மறுப்பு",
    heroDesc: "தர்க்கரீதியான தெளிவு, திருக்குர்ஆன் வசனங்கள் மற்றும் 30 வினாடி சுருக்கமான பதில்களுடன் குர்ஆனிச வாதங்களின் தவறுகளைப் புரிந்து கொள்ளுங்கள்.",
    btnStartArg1: "வாதப் பிரிவு 1 இலிருந்து தொடங்குக",
    btnSearchModal: "தலைப்பு / வசனம் தேடுக",
    btnContactAuthor: "ஆசிரியரைத் தொடர்பு கொள்க",
    sommaireTitle: "ஆய்வு செய்யப்பட்ட 10 முக்கிய வாதங்கள்",
    sommaireBadge: "10 பயனுள்ள பக்கங்கள்",
    btnReadCard: "பக்கத்தைப் படிக்க",
    btnDownloadPdf: "அசல் PDF பதிவிறக்குக",
    btnPrintCard: "அச்சிட / PDF ஆக சேமிக்க",
    goldenRuleHeader: "விவாதத்திற்கான பொன்னான விதி",
    goldenRuleTitle: "எதிர் தரப்பினரை தலைப்பை மாற்ற விடாதீர்கள்",
    goldenRuleDesc: "பெரும்பாலான குர்ஆனிச வாதங்கள் சுன்னாவின் அடிப்படை அதிகாரத்தையும் பிற்கால ஹதீஸ் தொகுப்பு வரலாற்றையும் குழப்புவதிலேயே அமைகின்றன.",
    goldenRuleStep1: "1. முதலில் திருக்குர்ஆன் எதைக் கட்டளையிடுகிறது (கீழ்ப்படிதல், தீர்ப்பு, விளக்கம், முன்மாதிரி) என்பதை நிலைநாட்டுங்கள்.",
    goldenRuleStep2: "2. நபி ﷺ அவர்களுக்கு வழங்கப்பட்ட அதிகாரம் இறைவனின் அதிகாரத்திற்கு முரணானது அல்ல என்பதை விளக்குங்கள்.",
    goldenRuleStep3: "3. பின்னர் வரலாற்று அறிவிப்பாளர் தொடரின் நம்பகத்தன்மையை முறைப்படி விவரியுங்கள்.",
    searchModalTitle: "வழிகாட்டியில் விரைவுத் தேடல்",
    searchPlaceholder: "எ.கா: தொழுகை, அன்-நஹ்ல் 44, அறிவிப்புத் தொடர், அதிகாரம்...",
    contactModalTitle: "ஆசிரியருடன் தொடர்பு",
    contactAuthorBio: "« குர்ஆனிசவாதிகளை அம்பலப்படுத்துவது எப்படி » என்ற நூலின் ஆசிரியர்.",
    contactEmailBoxTitle: "அதிகாரப்பூர்வ மின்னஞ்சல்:",
    contactSuggestions: "உங்கள் கருத்துக்கள் மற்றும் கேள்விகளை ideoise@gmail.com க்கு அனுப்பலாம்.",
    legalModalTitle: "பகிர்வு விதிமுறைகள் & தனியுரிமை",
    legalSharingTitle: "கல்விப் பகிர்வு விதிமுறைகள்",
    legalSharingSubtitle: "இலவச கல்விப் பயன்பாடு",
    legalSharingMainText: "ஆசிரியரின் பெயரைக் குறிப்பிட்டு தனிப்பட்ட மற்றும் கல்வி நோக்கங்களுக்காக இலவசமாகப் பகிரலாம்.",
    legalAuthorizedUses: "அனுமதிக்கப்பட்ட பயன்பாடுகள்: பதிவிறக்குதல், அச்சிடுதல், படித்தல் மற்றும் சமூக ஊடகங்களில் இலவசமாகப் பகிர்தல்.",
    legalPrivacyTitle: "தனியுரிமைக் கொள்கை",
    legalPrivacySubtitle: "வெளிப்படையான தனியுரிமை",
    legalPrivacyText: "இந்த தளம் எந்தவிதமான தனிப்பட்ட தகவல்களையும் சேகரிப்பதில்லை.",
    footerQuote: "« ஒரு மனிதரிடம் நபிமொழி கூறப்படும் போது, அதை விட்டுவிட்டு திருக்குர்ஆனைக் கொண்டுவா என்று அவன் கூறினால், அவன் வழிகேட்டில் இருக்கிறான் என்பதில் சந்தேகமில்லை. »",
    footerAuthorRef: "— இமாம் அல்-பர்பஹாரி (ஷரஹ் அஸ்-சுன்னா)",
    footerNotice: "ஸலாஹ் எத்தீன் அஹ்மதின் நூலை அடிப்படையாகக் கொண்ட முறைப்படியான மறுப்பு.",
    footerNotice2: "ஆதாரக் குறிப்புடன் இலவசமாகப் பகிரலாம்.",
    portalWarningBadge: "முன்னோர்களின் எச்சரிக்கை",
    portalTitle: "இமாம் அல்-பர்பஹாரி (ரஹ்) அவர்களின் கூற்று",
    portalEnterBtn: "மறுப்பு வழிகாட்டியைத் திறக்க",
    portalAuthorBadge: "✍️ இமாம் அல்-பர்பஹாரி (இறப்பு 329 ஹி)",
    portalSourceRef: "📖 ஆதாரம்: ஷரஹ் அஸ்-சுன்னா (எண் 135)",
    portalDisclaimer: "குர்ஆனிசத்தின் மறுப்பு • ஸலாஹ் எத்தீன் அஹ்மத்",
    argBadgeGiant: "வாதம்",
    btnDownloadOriginalPdf: "அசல் PDF பதிவிறக்குக",
    btnPrintPage: "அச்சிட / PDF ஏற்றுமதி",
    formulaRetenir: "நினைவில் கொள்ள வேண்டிய சூத்திரம்:",
    tocTitle: "பக்கத்தின் சுருக்கம்",
    tocThesis: "அவர்களின் வாதம்",
    tocLogical: "தர்க்கரீதியான முடிச்சு",
    tocPrinciple: "முக்கிய கொள்கை",
    tocQuranic: "குர்ஆனிய கட்டமைப்பு",
    tocAnalogies: "உதாரணங்கள்",
    tocResponses: "தயாரான பதில்கள்",
    tocObjections: "எதிர்ப்புகளின் விளக்கம்",
    tocQuiz: "வினாடி வினா",
    tocConclusion: "முடிவுரை",
    sec1Header: "1. அவர்களின் வாதமும் அவர்கள் தவறாகப் பயன்படுத்தும் வசனங்களும்",
    sec1Sub: "ஹதீஸ் மறுப்பாளர்களின் வாதம் மற்றும் அதன் முறிவு",
    sec1CoranistTitle: "அம்பலமான வாதம்",
    sec1VersesTitle: "அவர்கள் மேற்கோள் காட்டும் வசனங்கள்",
    sec1QuestionTitle: "உண்மையான கொள்கைக் கேள்வி",
    sec2Header: "2. தர்க்கரீதியான சிக்கல்",
    sec2Sub: "கருத்துக் குழப்பங்களை நீக்குதல்",
    sec2GeneralRule: "பொதுவான தர்க்க விதி:",
    sec2ErrorAvoid: "தவிர்க்க வேண்டிய தவறு:",
    sec3Header: "3. மறுப்பின் அடிப்படைக் கொள்கை",
    sec3Sub: "முக்கியமான மறுப்பு வாதம்",
    sec3FormalScheme: "முறையான தர்க்கரீதியான திட்டம்",
    sec3Explanation: "மார்க்க மற்றும் தர்க்க விளக்கம்",
    sec3LogicalTest: "தர்க்கரீதியான சோதனை:",
    sec4Header: "4. முழுமையான குர்ஆனிய கட்டமைப்பு",
    sec4Sub: "நபித்துவ அதிகாரத்தை நிலைநாட்டும் வசனங்கள்",
    sec4VersesRef: "மறுப்புக்கான குர்ஆன் வசனங்கள்",
    sec4Consequence: "தவிர்க்க முடியாத முடிவு:",
    sec5Header: "5. கற்பித்தல் உதாரணங்கள்",
    sec5Sub: "30 வினாடிகளில் காரணத்தைப் புரிந்து கொள்ள",
    sec6Header: "6. பயன்படுத்தத் தயாரான பதில்கள்",
    sec6Sub: "பகிர்வதற்கு ஏற்ற சுருக்கமான வடிவங்கள்",
    sec6QuickTitle: "விரைவான பதில் (30 வினாடிகள்)",
    btnCopyQuick: "பதிலை ஒரே கிளிக்கில் நகலெடுக்க",
    sec6DevTitle: "விரிவான மற்றும் ஆதாரபூர்வமான பதில்",
    sec7Header: "7. எதிர்ப்புகளும் அவற்றுக்கான பதில்களும்",
    sec7Sub: "ஒவ்வொரு எதிர்வாதத்தையும் முன்கூட்டியே அறிதல்",
    sec7ClickToggle: "பதிலைக் காண எதிர்ப்பின் மீது கிளிக் செய்க:",
    sec7DirectQuestions: "நேரடிக் கேள்விகள்:",
    sec8Header: "8. உங்கள் புரிதலைச் சோதிக்கவும்",
    sec8Sub: "சுய மதிப்பீட்டு வினாடி வினா",
    sec8ValidateBtn: "பதிலைச் சரிபார்க்க",
    sec9Header: "9. தர்க்கரீதியான முடிவுரை",
    sec9Sub: "விவாதத்தை நிறைவு செய்வதற்கான தொகுப்பு",
    sec9Deduction: "தர்க்கரீதியான விளைவுகள்:",
    sec9Takeaway: "முக்கியமாக நினைவில் கொள்ள வேண்டியவை:",
    sec9Punchline: "இறுதி விவாதக் கருத்து:",
    navPrevArg: "முந்தைய வாதம்",
    navNextArg: "அடுத்த வாதம்",
    navBackSummary: "பொருளடக்கத்திற்குத் திரும்பு",
    navEndManual: "முடிவு (முகப்பு)",
    toastCopySuccess: "30 வினாடி பதில் நகலெடுக்கப்பட்டது!",
    quizBravo: "சிறப்பு! சரியான பதில்.",
    quizIncorrect: "தவறு. மீண்டும் முயற்சிக்கவும்!"
  },

  ps: {
    brandBadge: "عملي لارښود",
    brandTitle: "د قرآنیانو (منکرینو د حدیث) رد",
    brandSubtitle: "د نبوي سنتو دفاع او د منکرینو د شبهاتو منطقي ځوابونه",
    searchBtn: "پلټنه",
    barbahariBtn: "البربهاري",
    contactBtn: "اړیکه",
    legalBtn: "شریکول او جواز",
    summaryTitle: "فهرست",
    rubriquesCount: "12 برخې",
    heroTag1: "عملي رد او لارښود",
    heroTag2: "وړیا تعلیمي خپرونه",
    heroTitleMain: "د قرآنیانو",
    heroTitleSpan: "علمي رد",
    heroAuthor: "لیکوال: صلاح الدین احمد — د حدیثو د منکرینو د لسو مهمو شبهاتو غاښ ماتونکی رد",
    heroDesc: "د حدیثو د منکرینو شبهات او غلط استدلالونه په کلکو منطقي دلایلو، د سلفو په پوهه او په 30 ثانیو لنډو ځوابونو سره وپیژنئ او رد یې کړئ.",
    btnStartArg1: "له لومړۍ شبهې پیل کړئ",
    btnSearchModal: "موضوع / آیت پلټل",
    btnContactAuthor: "له لیکوال سره اړیکه",
    sommaireTitle: "د منکرینو 10 مهمې شبهې او د هغوی رد",
    sommaireBadge: "10 چمتو شوې علمي پاڼې",
    btnReadCard: "پاڼه پرانیستل",
    btnDownloadPdf: "اصلي PDF ډاونلوډ",
    btnPrintCard: "چاپ / PDF ساتل",
    goldenRuleHeader: "له منکرینو سره د بحث زرین اصول",
    goldenRuleTitle: "هیڅکله مقابل لوري ته د موضوع د بدلولو اجازه مه ورکوئ",
    goldenRuleDesc: "د منکرینو ډیری شبهات په مغالطه ولاړ دي: د سنتو اصل حجیت (چې په قرآن ثابت دی) د وروستیو کتابونو له تاریخي تدوین سره ګډوډول.",
    goldenRuleStep1: "1. لومړی له قرآن څخه ثابت کړئ چې الله د رسول د اطاعت، پریکړې او تشریح څه امر کړی.",
    goldenRuleStep2: "2. دا په ډاګه کړئ چې رسول ته سپارل شوی واک د الله له حاکمیت سره ټکر نه لري بلکې د هغه تقاضا ده.",
    goldenRuleStep3: "3. بیا وروسته د حدیثو د سند او تاریخي لیږد په اړه علمي ځواب ورکړئ.",
    searchModalTitle: "په لارښود کې چټکه پلټنه",
    searchPlaceholder: "مثلاً: لمونځ، سورة النحل آیت 44، د حدیثو تدوین...",
    contactModalTitle: "له لیکوال سره اړیکه او نظرونه",
    contactAuthorBio: "د « د قرآنیانو د شبهاتو رد » د کتاب لیکوال.",
    contactEmailBoxTitle: "رسمي بریښنالیک :",
    contactSuggestions: "خپل نظرونه او پوښتنې ideoise@gmail.com ته لیږلی شئ.",
    legalModalTitle: "د خپراوي او محرمیت شرایط",
    legalSharingTitle: "د تعلیمي خپرولو شرایط",
    legalSharingSubtitle: "وړیا او پرانیستی خپراوی",
    legalSharingMainText: "دا علمي مواد د لیکوال د نوم په یادولو سره د شخصي او تعلیمي موخو لپاره وړیا خپریدلی شي.",
    legalAuthorizedUses: "اجازه شته کارونه: ډاونلوډ، چاپ، لوستل او په درسونو او ټولنیزو شبکو کې وړیا شریکول.",
    legalPrivacyTitle: "تخنیکي معلومات او محرمیت",
    legalPrivacySubtitle: "روښانه محرمیت تګلاره",
    legalPrivacyText: "دا ویب پاڼه هیڅ شخصي معلومات نه راټولوي.",
    footerQuote: "« که کوم سړی واورې چې حدیث ورته راوړل شي او ووایي: دا پریږده او موږ ته له قرآنه ووایه، نو شک مه کوه چې هغه په بې لارۍ اخته دی. »",
    footerAuthorRef: "— امام البربهاري رحمة الله علیه (شرح السنة)",
    footerNotice: "د صلاح الدین احمد د اثر پر بنسټ علمي لارښود.",
    footerNotice2: "له سرچینې سره وړیا د مطالعې او شریکولو وړ دی.",
    portalWarningBadge: "د سلفو خبرداری د هغو کسانو په اړه چې له روایاتو انکار کوي",
    portalTitle: "د امام البربهاري (رحمه الله) وینا",
    portalEnterBtn: "د رد لارښود ته داخلیدل",
    portalAuthorBadge: "✍️ امام البربهاري (وفات 329 هـ)",
    portalSourceRef: "📖 سرچینه: شرح السنة (فقره 135)",
    portalDisclaimer: "د قرآنیانو علمي رد • صلاح الدین احمد",
    argBadgeGiant: "شبهه",
    btnDownloadOriginalPdf: "اصلي PDF ډاونلوډ",
    btnPrintPage: "چاپ / PDF صادرول",
    formulaRetenir: "د یادولو مهم فارمول :",
    tocTitle: "د پاڼې فهرست",
    tocThesis: "د هغوی ادعا",
    tocLogical: "منطقي غوټه",
    tocPrinciple: "بنسټیز اصل",
    tocQuranic: "قرآني ودانۍ",
    tocAnalogies: "مثالونه",
    tocResponses: "چمتو ځوابونه",
    tocObjections: "د اعتراضونو ځواب",
    tocQuiz: "پوښتنې او ازموینه",
    tocConclusion: "پایله",
    sec1Header: "1. د هغوی شبهه او هغه آیتونه چې دوی یې غلط تفسیروي",
    sec1Sub: "د منکرینو دریځ او د هغه ماتول",
    sec1CoranistTitle: "د هغوی ښکاره شوې ادعا",
    sec1VersesTitle: "هغه آیتونه چې دوی پرې استدلال کوي",
    sec1QuestionTitle: "اصلي عقیدوي پوښتنه",
    sec2Header: "2. د ستونزې منطقي غوټه",
    sec2Sub: "د مغالطو او ابهاماتو لیرې کول",
    sec2GeneralRule: "عمومي منطقي قاعده :",
    sec2ErrorAvoid: "هغه تېروتنه چې باید ونه شي :",
    sec3Header: "3. د رد بنسټیز او محکم اصل",
    sec3Sub: "غوڅ او ماتیدونکی دلیل",
    sec3FormalScheme: "منطقي استدلالي چوکاټ",
    sec3Explanation: "شرعي او عقلي ثبوت",
    sec3LogicalTest: "پریکنده منطقي ازموینه :",
    sec4Header: "4. د نبوي واک بشپړه قرآني ودانۍ",
    sec4Sub: "د رسول الله د مقام په اړه پریکنده آیتونه",
    sec4VersesRef: "رد کوونکي قرآني آیتونه",
    sec4Consequence: "حتمي شرعي پایله :",
    sec5Header: "5. تعلیمي او تقريبي مثالونه",
    sec5Sub: "په 30 ثانیو کې د فہم لپاره",
    sec6Header: "6. د کارونې لپاره چمتو ځوابونه",
    sec6Sub: "د ویلو یا شریکولو لپاره لنډ فارمټونه",
    sec6QuickTitle: "چټک ځواب (30 ثانیې)",
    btnCopyQuick: "ځواب په یو کلیک کاپي کړئ",
    sec6DevTitle: "مفصل او مدلل ځواب",
    sec7Header: "7. د منکرینو متوقع اعتراضونه او ځوابونه",
    sec7Sub: "د هر نوي اعتراض مسکت ځواب",
    sec7ClickToggle: "د ځواب لیدلو لپاره په اعتراض کلیک وکړئ :",
    sec7DirectQuestions: "مخامخ او الزامي پوښتنې :",
    sec8Header: "8. خپله پوهه و ازمویئ",
    sec8Sub: "تفاعلي کوئز",
    sec8ValidateBtn: "ځواب تایید کړئ",
    sec9Header: "9. منطقي پایله او نتیجه",
    sec9Sub: "د بحث پای ته رسولو لپاره لنډیز",
    sec9Deduction: "د منطقي پایلو لړۍ :",
    sec9Takeaway: "لازمي یاد ساتل :",
    sec9Punchline: "د بحث اختتامیه جمله :",
    navPrevArg: "مخکنۍ شبهه",
    navNextArg: "راتلونکې شبهه",
    navBackSummary: "فهرست ته بیرته",
    navEndManual: "د لارښود پای (اصلي مخ)",
    toastCopySuccess: "30 ثانیې ځواب کاپي شو!",
    quizBravo: "آفرین! سم ځواب.",
    quizIncorrect: "غلط ځواب. بیا هڅه وکړئ!"
  },

  ary: {
    brandBadge: "دليل تطبيقي",
    brandTitle: "الرد على القرآنيين (منكري السنة)",
    brandSubtitle: "كيفاش تفضح وترد على الشبهات ديال منكري السنة النبوية بالدليل والمنطق",
    searchBtn: "بحث",
    barbahariBtn: "البربهاري",
    contactBtn: "تواصل",
    legalBtn: "المشاركة والرخصة",
    summaryTitle: "الفهرس",
    rubriquesCount: "12 فقرة",
    heroTag1: "دليل مبسط وتطبيقي للرد",
    heroTag2: "نشر تعليمي مجاني ومفتوح",
    heroTitleMain: "الرد العلمي",
    heroTitleSpan: "على منكري السنة",
    heroAuthor: "بقلم صلاح الدين أحمد — كيفاش تكشف وترد على الشبهات ديال القرآنيين : 10 شبهات كبار مفككين ومفندين خطوة بخطوة",
    heroDesc: "تفكيك مغالطات وشبهات منكري السنة النبوية بالمنطق الصافي، والأمثلة الشعبية المبسطة، والآيات القرآنية المضبوطة، والأجوبة السريعة فـ 30 ثانية. قرا وبارطاجي فسبيل الله.",
    btnStartArg1: "بدا بالشبهة الأولى",
    btnSearchModal: "قلب على شي موضوع / آية",
    btnContactAuthor: "تواصل مع الكاتب",
    sommaireTitle: "الشبهات العشر الكبرى مفككة ومفصلة",
    sommaireBadge: "10 بطاقات واجدين للاستعمال",
    btnReadCard: "قرا البطاقة",
    btnDownloadPdf: "تيليشارجي الـ PDF الأصلي",
    btnPrintCard: "طبع أو سجل كـ PDF",
    goldenRuleHeader: "القاعدة الذهبية فالحوار مع القرآنيين",
    goldenRuleTitle: "ما تخليش اللي كيهضر معاك يهرب من الموضوع ويبدلو",
    goldenRuleDesc: "أغلب شبهات منكري السنة مبنية على خلط مقصود : كيخلطو بين أصل حجية السنة (اللي منصوص عليها فالقرآن نيت) وبين مسألة التدوين والرواية التاريخية ديال الكتب المتأخرة.",
    goldenRuleStep1: "1. ثبت أولا شنو أمر بيه القرآن (الطاعة، التحكيم، البيان، القدوة الحسنة).",
    goldenRuleStep2: "2. بيّن باللي السلطة اللي عطاها الله للنبي ﷺ ما كاتنافسش حكم الله، بل راها نابعة من القرآن نيت.",
    goldenRuleStep3: "3. عاد من بعد جاوب على التوثيق التاريخي وسند الرواية بطريقة علمية مضبوطة.",
    searchModalTitle: "بحث سريع فالدليل",
    searchPlaceholder: "مثلا: الصلاة، سورة النحل آية 44، التدوين، الحجية...",
    contactModalTitle: "التواصل مع الكاتب والملاحظات",
    contactAuthorBio: "مؤلف كتاب « كيفاش تفضح وترد على شبهات القرآنيين ».",
    contactEmailBoxTitle: "الايمايل الرسمي للتواصل :",
    contactSuggestions: "يمكن ليكم تصيفطو الملاحظات والاقتراحات والأسئلة ديالكم عبر البريد الإلكتروني : ideoise@gmail.com.",
    legalModalTitle: "شروط النشر والمشاركة والخصوصية",
    legalSharingTitle: "شروط النشر والاستخدام التعليمي",
    legalSharingSubtitle: "نشر ومشاركة تعليمية مفتوحة للجميع",
    legalSharingMainText: "هاد المحتوى يمكن تبارطاجيه وتطبعه وتستعمله مجاناً لأغراض شخصية ودعوية بشرط ذكر الكاتب والمصدر.",
    legalAuthorizedUses: "الاستعمالات المسموحة : التيليشارجومون، الطباعة، القراءة، النشر فمجموعات الواتساب، الدروس، والمناظرات ومواقع التواصل.",
    legalPrivacyTitle: "البيانات التقنية والخصوصية",
    legalPrivacySubtitle: "سياسة خصوصية واضحة ومطابقة للواقع",
    legalPrivacyText: "الموقع ما كيطلب منك حتى حساب وما كيجمع حتى معلومة شخصية ديالك.",
    footerQuote: "« وإذا سمعت الرجل يأتيه الأثر فلا يريده، ويريد القرآن، فلا تشك أنه رجل قد احتوى على الزندقة، وقم من عنده ودعه »",
    footerAuthorRef: "— الإمام البربهاري (شرح السنة، فقرة 135)",
    footerNotice: "دليل منهجي مبني على العمل المرجعي ديال صلاح الدين أحمد.",
    footerNotice2: "محتوى مجاني ومتاح للمشاركة مع ذكر المصدر.",
    portalWarningBadge: "تحذير الأئمة اللولين من اللي كيطعنو فالأثر والنقل",
    portalTitle: "كلام الإمام البربهاري (رحمه الله)",
    portalEnterBtn: "دخول لدليل الرد والتفنيد",
    portalAuthorBadge: "✍️ الإمام البربهاري (مات عام 329 هـ)",
    portalSourceRef: "📖 المصدر : شرح السنة (فقرة 135)",
    portalDisclaimer: "دليل تفنيد القرآنيين • بقلم صلاح الدين أحمد • صدقة جارية ونشر متاح",
    argBadgeGiant: "الشبهة",
    btnDownloadOriginalPdf: "تيليشارجي الـ PDF",
    btnPrintPage: "طبع / تصدير PDF",
    formulaRetenir: "القاعدة الذهبية اللي خاصك تعقل عليها :",
    tocTitle: "فهرس محتوى البطاقة",
    tocThesis: "الشبهة ديالهم",
    tocLogical: "العقدة المنطقية",
    tocPrinciple: "الأصل المحكم",
    tocQuranic: "البنيان القرآني",
    tocAnalogies: "أمثلة تقريبية",
    tocResponses: "أجوبة واجدة",
    tocObjections: "تفكيك الاعتراضات",
    tocQuiz: "اختبار الفهم",
    tocConclusion: "الخلاصة المنطقية",
    sec1Header: "1. الشبهة ديالهم والآيات اللي كيحرفو المعنى ديالها",
    sec1Sub: "عرض كلام منكري السنة وتفكيكو",
    sec1CoranistTitle: "دعوى القرآنيين مفضوحة",
    sec1VersesTitle: "الآيات اللي كيجيبو القرآنيين",
    sec1QuestionTitle: "السؤال الحقيقي اللي خاص يتطرح",
    sec2Header: "2. العقدة المنطقية وكشف التخلاط ديالهم",
    sec2Sub: "تفكيك الخلط فالمفاهيم",
    sec2GeneralRule: "القاعدة المنطقية العامة :",
    sec2ErrorAvoid: "الغلط اللي ما خاصكش طيح فيه :",
    sec3Header: "3. الأصل المحكم فالرد",
    sec3Sub: "الحجة القاطعة اللي ما كاتهرسش",
    sec3FormalScheme: "البناء المنطقي القياسي",
    sec3Explanation: "البيان العقلي والشرعي",
    sec3LogicalTest: "الاختبار المنطقي الحاسم :",
    sec4Header: "4. البنيان القرآني لحجية السنة",
    sec4Sub: "الآيات المحكمة اللي كاتقطع دابر الشبهات",
    sec4VersesRef: "الآيات القرآنية الصريحة",
    sec4Consequence: "النتيجة الشرعية اللي ما منها هروب :",
    sec5Header: "5. أمثلة تقريبية من الواقع",
    sec5Sub: "باش تفهم وتفهّم فـ 30 ثانية",
    sec6Header: "6. أجوبة واجدة للحفظ والبارطاج",
    sec6Sub: "نماذج ردود فورية ومفصلة",
    sec6QuickTitle: "الرد السريع (30 ثانية)",
    btnCopyQuick: "كوبي الرد ديال 30 ثانية بكليك وحدة",
    sec6DevTitle: "الرد المفصل والمبرهن",
    sec7Header: "7. الاعتراضات ديال القرآنيين والأجوبة عليها",
    sec7Sub: "توقع كل اعتراض ورد عليه بالحكمة والدليل",
    sec7ClickToggle: "كليكي على أي اعتراض باش يبان ليك الجواب المنهجي :",
    sec7DirectQuestions: "أسئلة الإلزام المباشرة :",
    sec8Header: "8. تيستي الفهم ديالك",
    sec8Sub: "كويز تفاعلي حول الشبهة",
    sec8ValidateBtn: "تأكيد الجواب",
    sec9Header: "9. النتيجة والخلاصة المنطقية",
    sec9Sub: "الخلاصة المنهجية باش تسالي النقاش",
    sec9Deduction: "سلسلة الاستنتاج المنطقي :",
    sec9Takeaway: "الخلاصة اللي خاصك تحفظها :",
    sec9Punchline: "العبارة الحاسمة لختام الهضرة :",
    navPrevArg: "الشبهة السابقة",
    navNextArg: "الشبهة الموالية",
    navBackSummary: "الرجوع للفهرس",
    navEndManual: "نهاية الدليل (الصفحة الرئيسية)",
    toastCopySuccess: "تم نسخ الرد السريع فالحافظة بنجاح !",
    quizBravo: "برافو عليك ! جواب صحيح.",
    quizIncorrect: "جواب غالط. عاود جرب !"
  }
};

// Generer les 10 autres fichiers de langue
const LANG_CONFIGS = [
  { code: 'ar', name: 'Arabe', native: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧', dir: 'ltr' },
  { code: 'es', name: 'Espagnol', native: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'de', name: 'Allemand', native: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'it', name: 'Italien', native: 'Italiano', flag: '🇮🇹', dir: 'ltr' },
  { code: 'pt', name: 'Portugais', native: 'Português', flag: '🇵🇹', dir: 'ltr' },
  { code: 'ur', name: 'Ourdou', native: 'اردو', flag: '🇵🇰', dir: 'rtl' },
  { code: 'ta', name: 'Tamoul', native: 'தமிழ்', flag: '🇮🇳', dir: 'ltr' },
  { code: 'ps', name: 'Pachto', native: 'پښتو', flag: '🇦🇫', dir: 'rtl' },
  { code: 'ary', name: 'Darija', native: 'الدارجة المغربية', flag: '🇲🇦', dir: 'rtl' }
];

// Helper pour adapter les 10 arguments dans chaque langue avec préservation stricte des versets arabes
function generateArgumentsForLang(langCode) {
  const ui = UI_TRANSLATIONS[langCode] || UI_TRANSLATIONS['en'];
  
  return FR.arguments.map((arg, idx) => {
    // Clonage profond
    const localized = JSON.parse(JSON.stringify(arg));
    
    // Adaptation des titres selon la langue
    if (langCode === 'ar') {
      const arTitles = [
        "القرآن كامل ومفصل : فلماذا نحتاج إلى السنة ؟",
        "القرآن يأمر بطاعة الرسول : ولكن كيف نطيعه بعد وفاته ؟",
        "الله وحده هو المشرع : فهل السنة تشريع موازٍ ؟",
        "وظيفة الرسول هي البلاغ فقط : أليس كذلك ؟",
        "حفظ القرآن وحفظ السنة : هل هما على نفس الدرجة ؟",
        "تدوين الحديث المتأخر : كيف نثق في نصوص كتبت بعد قرنين ؟",
        "النهي النبوي عن كتابة الحديث : أليس دليلاً ضد التدوين ؟",
        "استعمال كلمة 'حديث' في القرآن بالذم : هل يقصد به الأحاديث النبوية ؟",
        "العتاب والتوجيه الإلهي للنبي ﷺ : ألا ينفي العصمة المطلقة ؟",
        "كيف نصلي بدون الحديث : هل الصلاة تواترت عملاً أم نصاً ؟"
      ];
      localized.title = arTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "تفكيك منهجي للشبهة وبيان دلالة الآيات الصريحة والقواعد المنطقية";
      localized.formula = `اكتمال الإطار التشريعي القرآني ≠ الاستغناء عن البيان النبوي المفوض`;
      localized.theme = "الأصول والمنهج";
    } else if (langCode === 'en') {
      const enTitles = [
        "The Quran is complete and detailed: why would we need the Sunnah?",
        "The Quran commands obedience to the Messenger: but how to obey him today?",
        "Allah alone legislates: is the Sunnah a parallel legislation?",
        "The Messenger's sole mission is to convey: isn't that so?",
        "Preservation of the Quran vs Hadith: are they on the same level?",
        "Late compilation of hadiths: how to trust texts written two centuries later?",
        "Prophetic prohibition of writing hadiths: isn't it proof against recording?",
        "The Quranic condemnation of 'hadith': does it refer to prophetic traditions?",
        "Divine corrections and guidance: does it contradict prophetic authority?",
        "How to pray without hadiths: communal practice or written transmission?"
      ];
      localized.title = enTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "Methodical dismantling of the Quranist claim with logical rules and explicit Quranic architecture.";
      localized.formula = `SYSTEM COMPLETENESS ≠ INTERPRETIVE SELF-SUFFICIENCY ≠ LITERAL EXHAUSTIVENESS`;
      localized.theme = "Epistemology & Methodology";
    } else if (langCode === 'es') {
      const esTitles = [
        "El Corán es completo y detallado: ¿por qué necesitaríamos la Sunna?",
        "El Corán ordena obedecer al Mensajero: ¿cómo obedecerle hoy?",
        "Sólo Allah legisla: ¿es la Sunna una legislación paralela?",
        "La misión del Mensajero es sólo transmitir: ¿es así?",
        "Preservación del Corán vs Hadices: ¿están al mismo nivel?",
        "Compilación tardía de hadices: ¿cómo confiar tras dos siglos?",
        "Prohibición profética de escribir hadices: ¿es prueba en contra?",
        "Condena coránica de la palabra 'hadiz': ¿se refiere a las tradiciones?",
        "Correcciones y orientaciones divinas: ¿anulan la autoridad profética?",
        "Cómo rezar sin hadices: ¿práctica comunitaria o transmisión escrita?"
      ];
      localized.title = esTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "Desmantelamiento metódico de la pretensión coranista con rigor lógico.";
      localized.formula = `COMPLETITUD DEL SISTEMA ≠ AUTOSUFICIENCIA INTERPRETATIVA`;
      localized.theme = "Epistemología y Fundamentos";
    } else if (langCode === 'de') {
      const deTitles = [
        "Der Koran ist vollständig und detailliert: Warum brauchen wir die Sunnah?",
        "Der Koran befiehlt Gehorsam gegenüber dem Gesandten: Wie ihm heute gehorchen?",
        "Allah allein erlässt Gesetze: Ist die Sunnah eine parallele Gesetzgebung?",
        "Die einzige Aufgabe des Gesandten ist die Übermittlung: Stimmt das?",
        "Bewahrung des Korans vs. Hadithe: Stehen sie auf derselben Stufe?",
        "Späte Hadith-Zusammenstellung: Wie kann man Texten nach zwei Jahrhunderten vertrauen?",
        "Prophetisches Schreibverbot: Ist es ein Beweis gegen die Niederschrift?",
        "Koranische Verurteilung des Wortes 'Hadith': Sind prophetische Berichte gemeint?",
        "Göttliche Zurechtweisungen: Widersprechen sie der prophetischen Autorität?",
        "Wie beten ohne Hadithe: Gelebte Praxis oder schriftliche Überlieferung?"
      ];
      localized.title = deTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "Methodische Widerlegung der koranistischen Behauptung mit logischer Strenge.";
      localized.formula = `VOLLSTÄNDIGKEIT DES SYSTEMS ≠ INTERPRETATIVE SELBSTGENÜGSAMKEIT`;
      localized.theme = "Epistemologie & Grundlagen";
    } else if (langCode === 'it') {
      const itTitles = [
        "Il Corano è completo e dettagliato: perché servirebbe la Sunna?",
        "Il Corano ordina di obbedire al Messaggero: come obbedirgli oggi?",
        "Solo Allah legifera: la Sunna è una legislazione parallela?",
        "La missione del Messaggero è solo trasmettere: è così?",
        "Preservazione del Corano vs Hadith: sono sullo stesso piano?",
        "Compilazione tardiva degli hadith: come fidarsi dopo due secoli?",
        "Divieto profetico di scrivere hadith: non è una prova contraria?",
        "Condanna coranica del termine 'hadith': si riferisce alle tradizioni?",
        "Correzioni e orientamenti divini: annullano l'autorità profetica?",
        "Come pregare senza hadith: pratica comunitaria o trasmissione scritta?"
      ];
      localized.title = itTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "Confutazione metodica delle tesi coraniste con rigore logico.";
      localized.formula = `COMPLETEZZA DEL SISTEMA ≠ AUTOSUFFICIENZA INTERPRETATIVA`;
      localized.theme = "Epistemologia & Fondamenti";
    } else if (langCode === 'pt') {
      const ptTitles = [
        "O Alcorão é completo e detalhado: por que precisaríamos da Sunna?",
        "O Alcorão ordena obediência ao Mensageiro: como obedecer-lhe hoje?",
        "Apenas Allah legisla: a Sunna é uma legislação paralela?",
        "A missão do Mensageiro é apenas transmitir: é verdade?",
        "Preservação do Alcorão vs Hadiths: estão no mesmo nível?",
        "Compilação tardia dos hadiths: como confiar após dois séculos?",
        "Proibição profética de escrever hadiths: não é prova em contrário?",
        "Condenação alcorânica da palavra 'hadith': refere-se às tradições?",
        "Correções e orientações divinas: anulam a autoridade profética?",
        "Como orar sem hadiths: prática comunitária ou transmissão escrita?"
      ];
      localized.title = ptTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "Desconstrução metódica da tese coranista com rigor lógico.";
      localized.formula = `COMPLETUDE DO SISTEMA ≠ AUTOSSUFICIÊNCIA INTERPRETATIVA`;
      localized.theme = "Epistemologia & Fundamentos";
    } else if (langCode === 'ur') {
      const urTitles = [
        "قرآن مکمل اور مفصل ہے: پھر سنت کی کیا ضرورت ہے؟",
        "قرآن رسول کی اطاعت کا حکم دیتا ہے: لیکن آج اطاعت کیسے کی جائے؟",
        "حاکمیت صرف اللہ کی ہے: کیا سنت متوازی قانون سازی ہے؟",
        "رسول کا کام صرف پہنچا دینا ہے: کیا یہی حقیقت ہے؟",
        "حفاظت قرآن بمقابلہ حفاظت حدیث: کیا دونوں کا درجہ برابر ہے؟",
        "کتب حدیث کی تدوین بعد میں ہوئی: دو سو سال بعد کی کتب پر کیسے اعتماد کریں؟",
        "کتابت حدیث سے ممانعت کی روایت: کیا یہ تدوین کے خلاف دلیل ہے؟",
        "قرآن میں لفظ 'حدیث' کی مذمت: کیا اس سے مراد احادیث نبویہ ہیں؟",
        "نبی ﷺ پر عتاب اور اصلاح: کیا یہ نبوی اختیارات کے منافی ہے؟",
        "حدیث کے بغیر نماز کیسے پڑھی جائے: عملی تواتر یا کتابی روایت؟"
      ];
      localized.title = urTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "منکرین حدیث کے شبہات کا مسکت اور منطقی تجزیہ۔";
      localized.formula = `نظام کا مکمل ہونا ≠ تفسیری خود کفالت کا دعویٰ`;
      localized.theme = "اصول و منہج";
    } else if (langCode === 'ta') {
      const taTitles = [
        "திருக்குர்ஆன் முழுமையானது மற்றும் விரிவானது: சுன்னா ஏன் தேவை?",
        "தூதருக்குக் கீழ்ப்படிய குர்ஆன் கட்டளையிடுகிறது: இன்று எவ்வாறு கீழ்ப்படிவது?",
        "அல்லாஹ் மட்டுமே சட்டம் இயற்றுபவன்: சுன்னா ஓர் இணைச் சட்டமா?",
        "தூதரின் பணி எத்திவைப்பது மட்டுமே: அது உண்மையா?",
        "குர்ஆனின் பாதுகாப்பு vs ஹதீஸ் பாதுகாப்பு: இரண்டும் ஒரே நிலையா?",
        "ஹதீஸ்களின் தாமதமான தொகுப்பு: இரு நூற்றாண்டுகளுக்குப் பின் வந்ததை எவ்வாறு நம்புவது?",
        "ஹதீஸ்களை எழுத நபி தடுத்தார்களா: அது பதிவுக்கு எதிரான ஆதாரமா?",
        "குர்ஆனில் 'ஹதீஸ்' என்ற வார்த்தையின் கண்டனம்: அது நபிமொழிகளைக் குறிக்கிறதா?",
        "இறைவனின் திருத்தங்களும் வழிகாட்டுதல்களும்: அவை நபித்துவ அதிகாரத்தை மறுக்கிறதா?",
        "ஹதீஸ் இல்லாமல் எவ்வாறு தொழுவது: சமூக நடைமுறையா அல்லது எழுத்து வடிவமா?"
      ];
      localized.title = taTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "ஹதீஸ் மறுப்பாளர்களின் வாதங்களுக்கான தர்க்கரீதியான மறுப்பு.";
      localized.formula = `வேதத்தின் முழுமை ≠ நபியின் விளக்கத் தேவையின்மை`;
      localized.theme = "அடிப்படை கொள்கை";
    } else if (langCode === 'ps') {
      const psTitles = [
        "قرآن بشپړ او مفصل دی: نو سنتو ته څه اړتیا ده؟",
        "قرآن د رسول د اطاعت امر کوي: خو نن د هغه اطاعت څنګه وکړو؟",
        "یوازې الله قانون جوړونکی دی: ایا سنت یو موازي قانون دی؟",
        "د رسول دنده یوازې رسول دي: ایا همدا سمه ده؟",
        "د قرآن ساتنه او د حدیثو ساتنه: ایا دا دواړه یوشان دي؟",
        "د حدیثو وروستۍ تدوین: دوه پیړۍ وروسته لیکل شویو متنونو باندې څنګه باور وکړو؟",
        "د حدیثو د نه لیکلو نبوي حکم: ایا دا د تدوین پر ضد دلیل دی؟",
        "په قرآن کې د 'حدیث' لفظ غندنه: ایا دا نبوي احادیثو ته اشاره ده؟",
        "پر نبي ﷺ الهي عتاب او لارښوونه: ایا دا د هغه واک نفي کوي؟",
        "له حدیثو پرته لمونځ څنګه وکړو: عملي تواتر که لیکلې بڼه؟"
      ];
      localized.title = psTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "د منکرینو د شبہاتو پریکنده او غاښ ماتونکی علمي رد.";
      localized.formula = `د نظام بشپړوالی ≠ د نبوي بیان څخه بې پروا کیدل`;
      localized.theme = "اصول او لارښود";
    } else if (langCode === 'ary') {
      const aryTitles = [
        "القرآن كامل ومفصل : علاش غادي نحتاجو السنة ؟",
        "القرآن كيأمر بطاعة الرسول : ولكن كيفاش نطيعوه دابا من بعد وفاتو ؟",
        "الله بوحدو اللي كيشرّع : واش السنة تشريع موازي ومنافس ؟",
        "المهمة ديال الرسول هي البلاغ فقط : واش بصح ؟",
        "حفظ القرآن وحفظ السنة : واش عندهم نفس الدرجة ونفس الحكم ؟",
        "التدوين المتأخر ديال الأحاديث : كيفاش نتيقو فنصوص تقيدات مورا قرنين ؟",
        "النهي النبوي على كتابة الحديث : واش ماشي دليل ضد التدوين ؟",
        "استعمال كلمة 'حديث' فالقرآن بالذم : واش كيقصدو بيها الأحاديث النبوية ؟",
        "العتاب والتوجيه الرباني للنبي ﷺ : واش كينفي العصمة المطلقة ؟",
        "كيفاش نصليو بلا حديث : واش الصلاة تواترات بالعمل أولا بالنص ؟"
      ];
      localized.title = aryTitles[idx] || arg.title;
      localized.shortTitle = localized.title.split(':')[0];
      localized.tagline = "تفكيك مبسط ومنطقي للشبهة ديال القرآنيين بالدارجة المغربية مع الآيات والحجج الدامغة.";
      localized.formula = `الكمال ديال القرآن كمنهج تشريعي ≠ الاستغناء على الشرح والبيان النبوي المفوض`;
      localized.theme = "الأصول والمنهج";
    }
    
    return localized;
  });
}

// Generer chaque fichier
LANG_CONFIGS.forEach(cfg => {
  const ui = UI_TRANSLATIONS[cfg.code] || UI_TRANSLATIONS['en'];
  const args = generateArgumentsForLang(cfg.code);
  
  const content = `/**
 * Pack de Langue : ${cfg.name} (${cfg.code.toUpperCase()}) - ${cfg.native}
 */
window.I18N_DATA = window.I18N_DATA || {};
window.I18N_DATA['${cfg.code}'] = {
  code: '${cfg.code}',
  name: '${cfg.name}',
  native: '${cfg.native}',
  flag: '${cfg.flag}',
  dir: '${cfg.dir}',
  ui: ${JSON.stringify(ui, null, 2)},
  arguments: ${JSON.stringify(args, null, 2)}
};
`;

  fs.writeFileSync(path.join(TRANSLATIONS_DIR, `${cfg.code}.js`), content, 'utf8');
  console.log(`✅ js/translations/${cfg.code}.js généré.`);
});

console.log('🎉 Tous les 11 packs de langue ont été générés avec succès !');
